### ISSUE TITLE
Duplicate Page IDs in the DOM

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#121]
PREVIOUS ISSUE TITLE: Theme doesn't get rendered

Sometimes, randomly, the theme will not get merged with the full node data, and I'll just get a screen like ...

{:panel:}{:header:}{:content:}{:footer:}

if I reload the app, goto the same node, it works, I get the rendered node data. I'm guessing the network dropped? But I've seen it happen on stable wifi as well.

Just noting it if others have experienced this.

**Comment by chrisschaub** [comment]
Ok, I've tracked down the offending piece of code. In includes/theme.inc.js, line 15 or so

``` javascript
// If the jqm active page url is the same as the page id of the current
// path, return.
if (drupalgap_jqm_active_page_url() == drupalgap_get_page_id(drupalgap_path_get())) {
  return;
}
```

causes this bug. To reproduce it, you have to show a list of teasers, maybe from a search. Click through, hit the back button, do another search and then click a teaser. The issue is that the "id" of my search page gets reused for each search, overwritten though. So, when you come back via the back button you trip this "if" statement and the template_preprocess doesn't fire. Is this code really needed?

**Comment by signalpoint** [comment]
@cschaub - thanks for more information on this issue. It sounds like it is definitely because of the same page id being used more than once. I've experienced strange behavior because of duplicate page ids in other locations as well.

I don't remember exactly what that boolean is used for, but it looks like it is used to prevent the page from being rebuilt if we're already on that page. It may be a remnant of pre drupalgap_goto() days since that function does prevent navigating (and rebuilding) of a page you are already on. This would need more testing though (this makes me think of how badly this project needs automated unit testing).

I'm going to rename this issue to indicate the need for a fix on the duplicate page id problem.

**Comment by signalpoint** [comment]
Lately https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/includes/go.inc.js has prevented duplicate pages in the DOM and allowed for the refreshing of the current page, I'll mark this one as resolved.
