### ISSUE TITLE
changePage function path

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#14]
It seems the drupalgap_changepage function is hard coded to an android path. I couldn't attach a patch file, so here goes:

function drupalgap_changePage(path) {
-       $.mobile.changePage('file:///android_asset/www/' + path);
-       $.mobile.changePage(path);
  }

Also, I think the jquery mobil changepage function supports not changing the url after the page changes. So, a click to dashboard.html would still show index.html# in the url bar, not /dashboard.html. I'm not sure if this is anything to consider as functionality, a switch maybe to not change the url? Maybe it's better to switch urls.

**Comment by chrisschaub** [comment]
Ha, well, it munged my attempt to insert a patch as plain text. The first line is wrong, the second works. Maybe there's a better approach in general though.

**Comment by signalpoint** [comment]
I believe @jnross has fixed this for us with this commit: https://github.com/signalpoint/DrupalGap/commit/eac23a9ad0a3be3213d60c6a762c02539cb6a10a

Thank you for the additional information. I'm still not convinced that the drupalgap_changePage function is a good idea, maybe we should get rid of it. I added it so it can be used by custom modules (e.g. https://github.com/signalpoint/dg_pro).

I'd really like to finish up the hook_menu implementation to have dynamic page generation instead of having all these .html files everywhere. The implementation is getting closer in the 7.x-1.x-dev branch
