### ISSUE TITLE
Attach onclick event to form element during form alter

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#151]
I wanted to execute a javascript function when onclick event happened in text field(for now). I tried attaching attribute property but it didnt work.

form.elements.field_status_date['attributes']={'onclick':"letscheck()"};

Is there another way to call the function during onclick.

Thanks.

**Comment by signalpoint** [comment]
@amitsedai - what type of form element is it? (e.g. text, select, checkbox, etc?)

**Comment by signalpoint** [comment]
@amitsedai - After a bit of research, this turned out to be a bug. Thanks for inquiring about this. Pull the latest changes for 7.x-1.x-alpha to get the fix.

Now, the correct syntax to use during hook_form_alter() would be something like this:

```
form.elements.my_element_name.options.attributes.onclick = "javascript:alert('hello');";
```

To verify which 'my_element_name' to use, try the dpm() function during form alteration, e.g:

```
dpm(form);
```

That will print the JSON object structure of the form to console.log().

**Comment by amitsedai** [comment]
Thanks. I did the same and it worked
form.elements.field_status_date.options['attributes']={'onclick':"letscheck()"};

Thanks again. Also I didnt know about dpm() method.

**Comment by signalpoint** [comment]
@amitsedai - good to hear. Please be careful with your line of code, because that overwrites the 'attributes' completely, which may interfere with some system defined attributes. Something like this is recommended instead:

```
form.elements.field_status_date.options['attributes'].onclick = "letscheck()";
```
