### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by sanee** [signalpoint/DrupalGap#152]
How to make a add a Google map in drupalgap, please help me.

**Comment by simonemarin** [comment]
Hi 
maybe look here?
https://developers.google.com/maps/documentation/javascript/examples/

if you better describe your needs we may give you a better help.
Simone

**Comment by liquidcms** [comment]
i think a typical application would be to make a request to Views to return a set of geofield locations which the app would then plot on a gmap.

**Comment by signalpoint** [comment]
@sanee 
@liquidcms 

DrupalGap Geofield has support for the Geofield Map display mode when using a GeoField on a content type: http://drupalgap.org/project/geofield

Otherwise, just include the google maps JS in your index.html, the use `hook_menu()` to make a page, a `page_callback` to make an empty map container and a `pageshow` callback that will manually fetch the Views JSON, then inject/init those coordinates into the map.

http://drupalgap.org/node/279
http://www.drupalgap.org/node/230

It would be fantastic if someone could write a page in the Getting Started guide about this topic(s)!

**Comment by liquidcms** [comment]
Yes, I am using geofield but not sure I know what or how “Geofield Map display mode” would work. I will be creating a map with a set of pins based on geofield items returned from a views call. So far I have just been using the basic gmap call and it is working to do a simple map; haven’t done call to get geofield data and place pins; but doubt that will be too difficult; doing this today.

If we get this all sorted out I may do a write up to explain.

**Comment by signalpoint** [comment]
@liquidcms OK, in your example you will not be using the "Geofield Map" display mode, that is simply to display a map when viewing a node (that has a geofield value) in the app. Happy coding!

**Comment by signalpoint** [comment]
I've added a complete example to the documentation: http://drupalgap.org/node/497
