### ISSUE TITLE
Basic list field not rendered

### ISSUE THREAD

**Issue by simonemarin** [signalpoint/DrupalGap#154]
Hi
the core list field is not rendered at node load.
json excerpt : 

```
"field_my_list": {

    "und": [
        {
            "value": "item1"
        }
    ]

}
```

**Comment by signalpoint** [comment]
@simonemarin - what's the console.log() warning thrown when this field fails to render? Whatever that is, that's the hook_field_formatter_view() that will need to be implemented in modules/field/field.js so DG understands the core list field.

Check out number_field_formatter_view() and text_field_formatter_view() in modules/field/field.js for other core field implementations.

**Comment by signalpoint** [comment]
@simonemarin I believe this problem is now resolved. For more information see here: http://www.drupalgap.org/node/184

I'd also recommend grabbing the latest dev snapshot of the module and SDK: http://drupalgap.org/download

If these two techniques do not resolve the issue, please let me know the exact Field Type and Widget that is specified on your manage fields pages, then we can re-open the issue:

```
admin/structure/types/manage/[my-custom-content-type]/fields
```
