### ISSUE TITLE
Content access and authentication

### ISSUE THREAD

**Issue by simonemarin** [signalpoint/DrupalGap#156]
Hi
some kind of authentication should be used to limit the access to the service only by the application to avoid others to be able to pull "clean" content with the json calls. 
Simone

**Comment by signalpoint** [comment]
Agreed. I've thought about this for a while now, and I keep leaning towards using an API key that would be available on our Drupal site (e.g. admin/config/drupalgap). Then that API key would be plugged into the app's settings.js file. Then all of the Service calls would need that API key passed along to verify the request is legitimate. This would require putting an API key check functionality on top of the Services module, so that may be a bit complex. I'm definitely open to other ideas on how to handle this issue.

**Comment by simonemarin** [comment]
https://drupal.org/project/services_basic_auth

**Comment by signalpoint** [comment]
After much thought, I don't think it is up to DrupalGap to make this happen, since DG is using the Services (and Views Dataource [Views JSON]) module to acquire the data. It'd be best to provide additional functionality for those contrib modules to support the idea of an API key.

Or as you mentioned, just using something like this may work as well:

https://drupal.org/project/services_basic_auth
