### ISSUE TITLE
some thoughts...

### ISSUE THREAD

**Issue by uniquename** [signalpoint/DrupalGap#17]
Hi,

I just came back here again and see great things going on! ..and wanted to leave some comments.

First, I came back here cause I was looking for the code, that i worked with a couple of month ago... but can't find it. Help me, if I'm wrong but, all the changes where commited in the 7.x-1.x branch... 
I thought it might be necessary to have a pattern like 7.x-1.2-1.0, where 1.2 represents the drupal module compatible with and third position is the version of the phonegap app.

In ripple and ios simulator I have an "error loading page" on the home button, with "...www/undefineddashboard.html" as link. Digged down to "window.fsroot" in function drupalgap_changePage. That also causes trouble when saving a node...

Really liked the complete drupalish way the app has now!

One last thought, wouldn't if be great to have something like node.tpl fieles to theme different content types?

cheers

p.s.: the issue tracker here should have some lables to organize and encourage discussions ;-)

**Comment by signalpoint** [comment]
Hi uniqename, welcome back!

Thank you for the kind words. Here's a rough timeline of the DrupalGap project on GitHub:

1.x - This was the first attempt at DrupalGap and was for both D6 and D7 sites.

7.x-2.x & 6.x-2.x - This was a complete overhaul of the first attempt, separate branches for D6 and D7 sites.

7.1-1.x & 6.x-1.x - (Recommended for now, this is probably the branch you are looking for) - Decided to roll back to a 1 froma  2, because a 2 wasn't appropriate since there isn't yet a solid 7.x-1.0 and 6.x-1.0 release.

7.x-1.x-dev - This is the bleeding edge and contains even more improvements.

There are some known issues with drupalgap_changePage. I'd like to use PhoneGap here to detect the operating system, and figure out the best path to use. Please let me know what works for your device(s). I really want to take a look at this soon, it is causing some problems for folks.

The node.tpl.php feature is a great idea, I've been tossing that around for a while and thinking of ways to accomplish it. Please let me know if you have any ideas.

If you'd like to see a DrupalCon Portland session about DrupalGap, please be so kind as to leave a brief comment here explaining why you'd like to see a session about DrupalGap. The session will be available on video afterwards I'm sure, thanks!

http://portland2013.drupal.org/session/drupalgap-mobile-application-development-kit-drupal

Please keep me posted on your development with DrupalGap, I'm glad to hear you are liking the progress.

**Comment by signalpoint** [comment]
P.S. I just added some labels to the issue queue.

**Comment by signalpoint** [comment]
I believe I have sorted out the drupalgap_changePage function for Android and iOS.

https://github.com/signalpoint/DrupalGap/issues/14

I'm very curious to see if this works for Ripple. I don't think it will. I haven't tried Ripple yet, so please contribute back and fixes you have for it.

I also added the feature request for node.tpl.php files into its own issue:

https://github.com/signalpoint/DrupalGap/issues/18

Closing this for now, please re-open or start a new one with any other support/feature requests, thanks!

**Comment by uniquename** [comment]
...a lable discussion would be great

**Comment by uniquename** [comment]
...commented on portland session, unfortunately to far a way to come ;-)

**Comment by signalpoint** [comment]
I have added a label for "Discussion" to the issue queue. Thank you for your support on the proposed session for DrupalCon Portland. I'll be sure to share the session video if we're lucky enough to present!

**Comment by uniquename** [comment]
github does not like me to pick a lable for a new issue...

**Comment by ghost** [comment]
"There are some known issues with drupalgap_changePage. I'd like to use PhoneGap here to detect the operating system, and figure out the best path to use. Please let me know what works for your device(s). I really want to take a look at this soon, it is causing some problems for folks."

I'm having the same 'drupalgap_changePage' for IOS, when pressing 'home'  I just get the 'Error Loading Page' . Any more ideas on a fix for this?

**Comment by signalpoint** [comment]
@botty, please check out this issue for more information:

https://github.com/signalpoint/DrupalGap/issues/14

Please feel free to re-open that issue if need be, thanks!
