### ISSUE TITLE
Using pagechange with drupalgap_goto using reloadPage makes App unresponsive

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#170]
Steps:
Created a menu:

```
'custom/%':{
      'title':'Custom Page',
      'page_arguments':[1],
      'page_callback':'custom_page',
      'pagechange':custom_page_pagechange',
       },
```

then executed `drupalgap_goto(drupalgap.back_path, {reloadPage:true});` inside the custom_page_pagechange.

This resulted in an error as follows:

```
Result of expression 'i.data("mobile-page")' [undefined] is not an object. at file:///android_asset/www/jquery.mobile-1.3.1.min.js:3
```

This is precisely the same error as logout used to have. Logout seems to have improved now :)

**Comment by amitsedai** [comment]
Update: 
If `drupalgap_goto(drupalgap.back_path)` is used without `{reloadPage:true}` option, then the redirection works fine for the first time. However, subsequent click on the link do not redirect back to the previous page.

**Comment by amitsedai** [comment]
Even for pageshow with `{reloadPage:true}`, its throwing the same error.

**Comment by signalpoint** [comment]
@amitsedai I hope this issue still doesn't bother you. If it does, I'd recommend just calling `drupalgap_back()` instead of doing `drupalgap_goto(drupalgap.back_path)`. I haven't ever needed to use the `pagechange` event, so I can't attest to what it can/can't do. I'll close this issue, due to inactivity.
