### ISSUE TITLE
Comments do not appear on node page

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#171]
Comments do not appear when node page is being viewed. The comment form appears though.

**Comment by signalpoint** [comment]
I believe this is related to #153 - we need to have the comment list use a unique id in node_page_view() and that should help with this problem. For example, instead of using 'comment_listing_items' as the id for the list, we should use 'comment_listing_items_' + nid for the id, that way each node has a unique list for its comments. When viewing more than one node, all subsequent nodes will just populate the first node's comment listing (since it is still in the DOM and they all have the same id).

**Comment by amitsedai** [comment]
Added the commit for the change. Works fine.

**Comment by amitsedai** [comment]
Display was an issue for node comments in the past. However, recent commits (before mine) seems to have fixed this. Comments do appear properly even without the commit made by me. However #153 may be an issue solved by this(I guess as I am not seeing this occurring for multiple comments in a page). Do use your judgement for including this commit.

**Comment by signalpoint** [comment]
This issue is resolved. The two related issues are #153 and #180.
