### ISSUE TITLE
Chrome ripple does not render data which uses $('#id').append(html) 

### ISSUE THREAD

**Issue by amitsedai** [signalpoint/DrupalGap#174]
To reproduce:

Page Callback:

content.somedata = {
    'markup':'< div id="someid" class="someclass">< /div > ',  
   };
- [Added Space to div to avoid rendering here]

Under pageshow which has a ajax for views:
$('#someid').append(html);

This works absolutely fine with any android device as well as with AVD(Android virtual device) used with eclipse/SDK. However it does not get displayed with Chrome ripple. 

For list based (jqm_item_list), it works fine.

**Comment by amitsedai** [comment]
Another example where it failed was when updating the image src  in pageshow:
$('#lic_image').attr('src', object.node.imageurl);

This works fine in the device and AVD

**Comment by signalpoint** [comment]
@amitsedai - Is it possible for example the #lic_image element exists on multiple pages? If that is the case, and there is already a page in the DOM with that element id, then any changes to that element will only be reflected on the first page with that id, not necessarily the page you are looking at. If that is the case, this is related to what we just fixed regarding the comment listing on nodes, where we had to append the node id to the comment listing id, so that each list gets a unique id.

**Comment by signalpoint** [comment]
@amitsedai Were you able to resolve this?

**Comment by amitsedai** [comment]
@signalpoint - The image existed only on a single page. I was not able to resolve this when I was working earlier. Unfortunately, I have not worked on DrupalGap after that.

**Comment by signalpoint** [comment]
OK, I'm marking as resolved, and I'm guessing it was because of duplicate ids being used within the DOM. Feel free to re-open if need be.
