### ISSUE TITLE
first page load

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#185]
So, drupalgap has a setting for the "front" page. Why not add some markup in index.html that has a default page who's id is that of the front page? That would prevent the load and switch page behaviour we have right now. It would speed up start time as well and make the transition from splash screen smoother. Right now an empty page is created and then the switch to the front. Just a thought.

**Comment by signalpoint** [comment]
@cschaub I could see adding a "splash" page (not the actual splash page that iOS and Android have while loading the app) to the index.html file, and have it be empty (or the developer can put whatever they want in it).

We won't be able to add markup to the index.html file and predict the page_id that will be used since each app's front page is potentially different.

Have you had any success using an approach that you described?

**Comment by signalpoint** [comment]
Duplicate issue listed here:

#46
