### ISSUE TITLE
PhoneGap 3.x Support

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#193]
PhoneGap 3.2 is out, we need to add support for 3.x gosh darn it!

This comment (https://drupal.org/comment/8155281#comment-8155281) shows just some of the things that need to happen when getting ready to support PhoneGap 3.x

**Comment by chrisschaub** [comment]
I've already used it with Cordova 3.x, works well.

On Sun, Dec 1, 2013 at 10:02 PM, Tyler Frankenstein <
notifications@github.com> wrote:

> PhoneGap 3.2 is out, we need to add support for 3.x gosh darn it!
> 
> This comment (https://drupal.org/comment/8155281#comment-8155281) shows
> just some of the things that need to happen when getting ready to support
> PhoneGap 3.x
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/signalpoint/DrupalGap/issues/193
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by signalpoint** [comment]
@cschaub - thanks Chris, that adds some relief to this. I tried a 3.1.0 the other day on a Mac, and it had all kinds of problems, so I'm not sure if I messed something up. Please feel free to share your experience and any changes you had to make to use 3.x, thanks!

**Comment by chrisschaub** [comment]
The biggest thing is adding in the plugins you need since 3.x is leaner.
Most of the issues I've had recently are not with Cordova, but IOS7. The
darn status bar is truly annoying. I had to use a plugin to get the
statusbar to really work on 6&7. Otherwise, Cordova 3 was a pretty smooth
upgrade.

On Sun, Dec 1, 2013 at 10:08 PM, Tyler Frankenstein <
notifications@github.com> wrote:

> @cschaub https://github.com/cschaub - thanks Chris, that adds some
> relief to this. I tried a 3.1.0 the other day on a Mac, and it had all
> kinds of problems, so I'm not sure if I messed something up. Please feel
> free to share your experience and any changes you had to make to use 3.x,
> thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/signalpoint/DrupalGap/issues/193#issuecomment-29593445
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by janexip** [comment]
I've tried with Cordova 3.2 and it works perfect. Followed instructions from the above mentioned comment, and it just works. Didn't even take 15 mins. Thanks!

**Comment by chrisschaub** [comment]
I have noticed then compiling for iOS and provisioning, there are issues with Cordova 3.1 and 3.2. 3.0 works great, but after that, deviceready is not working reliably -- doesn't fire.

https://issues.apache.org/jira/browse/CB-5037

**Comment by scotthooker** [comment]
Chris,

What was your status bar plugin/fix. Just looking at this now.

Probably a good idea to do a d.o kinda thing on drupalgap.org to have a knowledge base of that kinda stuff. 

P.s. I think I've finally got time to finish making a generic push notification plugin. Certainly will finish that off in the next week or so :)

**Comment by chrisschaub** [comment]
I used the StatusBar Cordova plugin and used the StatusBar.hide() function.
It works well, but only with Cordova 3.0. It wasn't compatible with 3.1 or
3.2 as of a week ago.

-c

On Wed, Jan 1, 2014 at 5:54 AM, scotthooker notifications@github.comwrote:

> Chris,
> 
> What was your status bar plugin/fix. Just looking at this now.
> 
> Probably a good idea to do a d.o kinda thing on drupalgap.org to have a
> knowledge base of that kinda stuff.
> 
> P.s. I think I've finally got time to finish making a generic push
> notification plugin. Certainly will finish that off in the next week or so
> :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/signalpoint/DrupalGap/issues/193#issuecomment-31421907
> .

## 

Christopher Schaub
http://chris.schaub.com

**Comment by ice423cube** [comment]
I've tried with Cordova 3.3 and it works ok using android. Followed instructions from the above mentioned comment(https://drupal.org/comment/8155281#comment-8155281), and it mostly works. I added in the suggested plugin and a couple more plugins but that is because my app needs more.  So far I have tested the following on the android emulator:
- Modules seem to great
- Themes seems to great 
- Login: Works
- View All Nodes: Works
- Edit node and Save: Save doesn't work.  Node edit page seems to load fine when you hit save it bombs.  The error shows: DrupalGap API Call Error, error(Method Not Implemented)<!DOCTYPE html... (it them seems to try to load the entire site with a status message of "Log in successful for admin".  (See images below)
  ![edit-node_1](https://f.cloud.github.com/assets/803478/1932744/12f0af5a-7ed0-11e3-9c71-b73eaa7b7637.png)
  ![edit-node-2](https://f.cloud.github.com/assets/803478/1932745/12f116ac-7ed0-11e3-9687-09f43b1e6027.png)) 
- Register - Register fails. The error shows DupalGap API Call Error, parsererror (SyntaxError: Unexpected token S)[OK].  The interesting thing is it still seems to create the account but then after you hit ok on the alert error message you get white screened of death. (See image below)

![register_account](https://f.cloud.github.com/assets/803478/1932746/12f12bec-7ed0-11e3-9004-afe5489d2358.png) 
- Taxonomy - works
- Users Listing - Works
- Logout - Doesn't logout and take you back to the home screen.  You get white screened of death after the logging out... page shows.

Hope that helps get a jump start on things.

**Comment by signalpoint** [comment]
Resolved with the 7.x-1.7-alpha release.

More info: http://drupalgap.org/node/193
