### ISSUE TITLE
Edit a Node - Styles are not jQueryMobile

### ISSUE THREAD

**Issue by ice423cube** [signalpoint/DrupalGap#197]
When i am logged in on the app (using ripple) and i got to a node and then hit edit.  I get to the edit page and it looks ok.  It is just not using the jquery mobile style sheet.  Do I need to do something to get it to use the style sheet?  When I create a new node it is styled appropriately.  I have attached images showing what i am talking about.

![create new node styled 2013-12-12_1628](https://f.cloud.github.com/assets/803478/1737526/b4fa633a-6374-11e3-9e28-c50149668ce6.png)
![edit node page no styling 2013-12-12_1629](https://f.cloud.github.com/assets/803478/1737527/b4fade50-6374-11e3-8227-15a6badb6dfc.png)

**Comment by signalpoint** [comment]
@ice423cube - thank you for the screen shots, that is very helpful. This seems to be a bug with the "new" Forms API when editing an entity (e.g. node).

This is because we are now building a page with an empty container, displaying the page, then making a call to Drupal (or local storage) for the entity, when that is returned to use we inject it into the page. In this case we are injecting a form using entity_page_edit_pageshow():

https://github.com/signalpoint/DrupalGap/blob/7.x-1.x-alpha/modules/entity/entity.js#L649

Somewhere down the line from there, we need to have jQM "refresh" (I think) all the form inputs so they will have the jQM styling applied. This will probably be similar to how drupalgap_item_list_populate() uses "refresh" to rebuild options in a select list.

https://github.com/signalpoint/DrupalGap/blob/7.x-1.x-alpha/drupalgap.js#L688
