### ISSUE TITLE
Form Element Placeholders

### ISSUE THREAD

**Issue by scotthooker** [signalpoint/DrupalGap#208]
In keeping with modern design themes form fields should be able to have a "placeholder" attribute to be set

**Comment by signalpoint** [comment]
@scotthooker I'm not sure what you mean by "placeholder". Please elaborate, thanks!

**Comment by scotthooker** [comment]
Basically infield labels http://www.w3schools.com/tags/att_input_placeholder.asp so rather than have the label above we can just set the placeholder attribute and have the label inside the field.

**Comment by signalpoint** [comment]
Interesting. I think we'll want to support both, and let the developer decide which one to use. In the mean time, hook_form_alter() can be used to accomplish this (sort of):

```
/**
 * Implements hook_form_alter().
 */
function my_module_form_alter(form, form_state, form_id) {
  try {
    if (form_id == 'node_edit') {
      form.elements.title.options.attributes['placeholder'] = form.elements.title.title;
      form.elements.title.title = '';
    }
  }
  catch (error) { console.log('my_module_form_alter - ' + error); }
}
```

**Comment by scotthooker** [comment]
Ah ok.

I was trying to do  form.elements.title.options.attributes.placeholder which doesn't work obviously. 

I think this is fine as this means we do support both.

**Comment by signalpoint** [comment]
Interesting. Technically these two lines of code are the same (I think):

form.elements.title.options.attributes.placeholder
form.elements.title.options.attributes['placeholder']

Strange that it doesn't work, oh well.

I've updated the documentation to include an example of how to do this:

http://drupalgap.org/node/209

I'm going to convert this into an "Improvement" issue. Ultimately I'd like to see us be able to just do this:

form.elements.title.placeholder = true;

And then the Forms API will auto render the placeholder instead of the label.

**Comment by scotthooker** [comment]
Gotcha.
