### ISSUE TITLE
DrupalGap sessions not persistant

### ISSUE THREAD

**Issue by scotthooker** [signalpoint/DrupalGap#211]
If I login and use the app all is fine. All of the visibility rules etc... are fired correctly.

If I close the app and reopen I am shown the login page again (with force authentication) despite the fact I am already logged in. If I try to login on this page it tells me I'm already logged in.

**Comment by scotthooker** [comment]
Correction. This is a weighting issue. When force_auth loads    console.log(Drupal.user.uid); returns 0.

As Drupal.user.uid isn't set yet.

**Comment by signalpoint** [comment]
What function does this happen inside https://github.com/signalpoint/force_authentication/blob/7.x-1.x/force_authentication.js ?

**Comment by scotthooker** [comment]
Yes so I'm not sure if this issue should sit with that contrib module. Or whether the issue in core is that "device ready" doesn't have all the appropriate variables set up for contrib modules to reliably use.

**Comment by signalpoint** [comment]
You're right. The Drupal.user object always reports as anonymous during hook_deviceready() because the System Connect resource hasn't been called yet. I've released a new version of the Force Authentication module with this fix:

https://github.com/signalpoint/force_authentication/releases

Yes, in the future, I'd like contrib module issues to land on their own issue queues, thanks!
