### ISSUE TITLE
Add Autocomplete Support for Taxonomy Term Reference Fields

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#224]

**Comment by biydnd** [comment]
First of all, thank you for the great Drupalgap project! 
I am slowly wading through docs and am able to build a bunch of features for my mobile app. Recently I have been stuck in a multiple-value taxonomy_term_reference field or the simple tags field. Here are my troubles:
1. On the node edit page, the taxonomy_term_reference field will not display the value or values that are already in the node.
2. The Drupalgap development code I have doesn't seem to support the multiple-value taxonomy_term_reference field. Or is it now?

Thank you for any light you can shed for my spinning brain!

**Comment by signalpoint** [comment]
@biydnd Correct, DrupalGap does not currently support unlimited value fields. It does support multi value fields (just not unlimited value fields). However, depending on the field and widget, things could be a little strange.

It sounds like there are indeed some bugs with a taxonomy term reference field that uses an auto complete widget. If I remember correctly, I have other widgets operating stable (select lists, radios, check boxes) for a taxonomy term reference field, but I think only a single value is working for autocomplete. That feature will need some love to be complete.

**Comment by biydnd** [comment]
Yes, this is the autocomplete widget. Do you think your code will not populate the tag value in the node? Since the autocomplete widget is done by the jquerymobile on(filterablebeforefilter), I had a hard time populating the value or default value in the field, even after I gave it so much love and time :(.

**Comment by biydnd** [comment]
I can hack the code to make muti-value work, but couldn't get the existing values populated in the field just like on the Drupal node edit page.

**Comment by signalpoint** [comment]
@biydnd First I would recommend pulling in the latest changes from DrupalGap into your fork: https://github.com/biydnd/DrupalGap

Then make a branch called "7.x-1.x-issue-224", and place your code "hacks" into there, commit them, and push them up to your repository. That'll allow us to take a look at your progress and we can better figure out how to solve all the issues.

**Comment by biydnd** [comment]
Thank you, but I have to figure out how to present my code. The critical hacks are in my custom module. Somehow I couldn't get the hook_form_alter for the node_edit work the way I wanted, so I created my own custom form for the node edit. I have another taxonomy term reference field with select widget, three options and allowing only one value. I got that working with the type select. For the tags field, I need it to work exactly like the field on Drupal, so I made the field_tags field in my form "is_field" by creating a custom version of "drupalgap_field_info_instances_add_to_form" for the field_tags field only. So you see, in my custom form, all fields except field_tags have is_field = false. With field_tags being is_field, it's able to fall through the is_field flow in the form and element rendering and presented as an autocomplete taxonomy widget. 

In my custom "drupalgap_field_info_instances_add_to_form", for node create, I use the " if(cardinality = -1) cardinality = 1" logic but commented it out if a node object is present and use the number of field_tags values in the node object passed in for the looping through items if a node object is present. For each item, I called drupalgap_form_element_item_create to create the content of each item and then merge the new content with the item already present in the node. Since I have been so stuck in trying to populate the tag values in the node, I haven't yet fully test if the multi-value hack will work. 

Other than my custom drupalgap_field_info_instances_add_to_form, I made some changes in the _taxonomy_field_widget_form_autocomplete to acknowledge comma in the input, also haven't fully tested yet.

Will update again with my code.

**Comment by signalpoint** [comment]
@biydnd Thanks for the update. Regarding the hook_form_alter() not working, that's because the taxonomy term reference field gets filled in after the page is displayed (via an async call to the server), and any form alterations take place before the page is displayed.

**Comment by biydnd** [comment]
I changed my code and a bunch of places in drupalgap.js to use the standard node_edit page and now all my fields including one of the taxonomy_term_reference fields with single value and option_select widget are working. The field_tags field with autocomplete widget is still not showing the current values in the node. I have created branch 7.x-1.x-issue-224 and submitted my changes in  drupalgap.js. A lot of random changes were made to support some specific settings in my app, such as a custom menu of xxxxx/%/% in drupalgap_get_menu_link_router_path() and mutivalue select in theme_select. 

The main changes made to solve the taxonomy_term_reference issues are in drupalgap_field_info_instances_add_to_form(). Other than the language issue that might be specific to my site only (my field_tags values are under 'en' and field_privacy under 'und'), others I think are for generic taxonomy_term_reference such as looping through values exist in entity for cardinality = -1 case and getting taxonomy values and tids from item.name and tid from item.tid. To display the existing value in the select widget of taxonomy term, I just removed the help text. For the autocomplete taxonomy_field_widget_form, I haven't been able to show existing values in the node however I tried. In the line 11016 console.log I was able to make sure that I have the correct value stored there (right now it's only the single value for this delta, but it's easy to get all the values in all delta if I can figure out how to display it in the autocomplete field). 

I hope the code will help you help me resolve this issue. Thank you !

**Comment by biydnd** [comment]
I think I got the taxonomy_term_reference autocomplete widget working for displaying the current values and for adding multiple values. I cannot get the JQueryMobile autocomplete "filterablebeforefilter" event to work for this case, so I change the taxonomy_term_reference item type from hidden to text input and  still use en empty item list just like before. Then use a .on('input') event on the input field to call the the same autocomplete method and execute the service call to get taxonomy terms. In the autocomplete method I took care to get only the term entered after the last comma and send for the list of suggested terms. Hopefully it's the same way that works on the Drupal node edit form. The code has been checked in.

Now I have to figure out if I can save the values in submit...

**Comment by biydnd** [comment]
Happy new year! Got side tracked for a while...

Just checked in some final changes for the taxonomy autocomplete field with multivalue.
Now the autocomplete field can populate existing value or values and can add or remove values. Upon submission, the values are stored in form_state and subsequently updated to the field of the node. A preliminary testing for an existing node is working fine. Haven't tested creating a new node. There must be bugs.

Tyler, I have a new problem and need some insight. I am forced to fix my problem with node view page or node/% now that I am using the node/%/edit page. Because my node doesn't have comments, the node/% page now only displays a title, not even the node body. This content type has only a title, a body and two taxonomy reference fields, one single value option select and the other autocomplete free tagging. In node_page_view_pageshow() on node_load success, the node.content is empty. Do I need to implement hood_field_formatter_view for even the body? Any idea? Thank you!

**Comment by signalpoint** [comment]
@biydnd Please open a new issue for the new request.
