### ISSUE TITLE
Phonegap required?

### ISSUE THREAD

**Issue by jaarong** [signalpoint/DrupalGap#23]
If I wanted to use Drupalgap as a layer for Services interaction on a mobile site (not app), is that possible?  Is that a bad idea or are there better options?

**Comment by signalpoint** [comment]
So far DrupalGap is largely just JS, jQuery, and jQM. There are a few spots that utilize PhoneGap (alert dialogs, drupalgap_changePage(), the camera, etc).

I don't think it is a bad idea to try to use DrupalGap as a layer for Services, I'd be curious to hear how it goes. I think it will work just fine because the DrupalGap Services API has minimal interaction with PhoneGap. I'd like to point out that the default 'error' call back on on API call does use the PhoneGap alert dialog, so the api.js file would need to be patched a bit to fall back to a normal javascript alert if PhoneGap isn't available.

Down the road, I would like to branch out DrupalGap into a strict JS library with a PhoneGap add on, but that is a ways out.

**Comment by jaarong** [comment]
Ok, thanks, even with PhoneGap, I don't think I can support all the different mobile operating systems that exist today, so an accompanying mobile site with the same look/feel/functionality is a major goal.
