### ISSUE TITLE
Cant find custom theme

### ISSUE THREAD

**Issue by quiquee** [signalpoint/DrupalGap#251]
This is probably some problem on my end , but I really cant figure out what the issue is. 
I have my own theme in settings:
// Theme
drupalgap.settings.theme = 'padelfirst';

And I have added my theme in app/themes/padelfirst

Drupalgap works if I create a link to this directory from the drupalgap/themes directory, but if I delete the link it doesnt try to find my theme under app/themes . How can I debug this?

Thanks !!

**Comment by signalpoint** [comment]
@quiquee This is a bug with DrupalGap, and it only seems to happen on certain platforms. Thank you for pointing out the temporary solution of just placing your custom theme (or a sym link) in the core themes directory instead of in the app/themes directory.

I believe the actual bug resides in drupalgap_load_theme(), which makes calls to drupalgap_file_exists(). It first tries to load the theme in the core directory, which seems to throw a 404 on some platforms when a custom theme is enabled.

So I'm fairly certain this 404 crashes some platforms. Therefore I think drupalgap_file_exists() needs to be modified to work and not throw a 404 when a file isn't found.

**Comment by quiquee** [comment]
Thank you for the answer. I am debugging under ripple. Hav you considered linking to the drupal module, so it provides some of the settings instead of using settings.js ? I mean, define an application in drupal and then define there some of the settings? to me that would sound like the behaviour I would have expected.

**Comment by signalpoint** [comment]
@quiquee Yes, I've considered offering settings inside of the Drupal module so they can be set through the Drupal website's UI. I've put that on the feature list for version 2.x of DrupalGap.

Please let me know if you find a way around the 404 vs. custom theme, thanks!

**Comment by signalpoint** [comment]
DG core no longer looks in first in the themes directory when it attempts to load a custom theme, instead it will automatically look in app/themes. Prior to this change, the old attempt was throwing 404/WSOD on some platforms.
