### ISSUE TITLE
Drupalgap and Phonegap Build

### ISSUE THREAD

**Issue by pasewebstudio** [signalpoint/DrupalGap#253]
Hi everyone,
is there a way to connect DrupalGap with Phonegap Build?

Thanks in advance
Cristina

**Comment by signalpoint** [comment]
@pasewebstudio I personally haven't tried PhoneGap build, but I know others have. Check out this issue for more info:

https://drupal.org/node/2230031

Essentially (if I remember correctly), make sure you have a config.xml file present in your build, and make sure phonegap.js is used in the index.html file instead of cordova.js

**Comment by pasewebstudio** [comment]
ok, thank you very much
