### ISSUE TITLE
Menu placeholder div messes up JQM listview styling

### ISSUE THREAD

**Issue by johnpitcairn** [signalpoint/DrupalGap#261]
The placeholder div that winds up wrapping a menu conflicts with jQuery Mobile's styling of listviews in some contexts.

Example: a menu with data-role="listview" placed inside a region with data-role="panel" results in a listview with unwanted margins, due to the extra wrapper div added by DrupalGap. The relevant JQM style rule which should remove the padding in this case is 

```
ui-panel > ui-listview
```

That wrapper div is presumably only there to allow the page callback to target a unique id. Couldn't the wrapper be removed after its contents have been added? For "all other menus" in menu_block_view_pageshow(), that's possibly as simple as:

```
$('#' + options.container_id).html(html).trigger('create').children().unwrap();
```

For primary local tasks, I'm not sure?

**Comment by signalpoint** [comment]
@johnpitcairn Yes, the div wrapper is so the menu's content can be injected on the pageshow event. I just added this change yesterday to get around a long standing problem with checking the drupalgap_menu_access() on menu link items, since some menu link items have their own access_callback and need an entity to be async loaded before determining the access #257 .

This issue only really occurs with primary local tasks (node view, node edit, etc), so for "all other menus" (and even the primary local tasks) I think it would be fine to unwrap them. Maybe this could be an option on the menu inside of settings.js so the wrapper could stay if necessary.

**Comment by johnpitcairn** [comment]
OK then ... a question about unwrapping local tasks - in menu_block_view_pageshow():

```
          // Inject the html.
          $('#' + options.container_id).html(html).trigger('create');
          // If the block's region is a jQM navbar, refresh the navbar.
          if (options['data-role'] && options['data-role'] == 'navbar') {
            $('#' + options.container_id).navbar();
          }
```

options['data-role'] is the data-role on the parent region container, not the data-role on the menu itself (confusing). Shouldn't this be calling navbar() on the region container, rather than on the wrapper?

**Comment by johnpitcairn** [comment]
OK, I think I have things working. I've added a "wrap" option - if present and true, this will not remove the placeholder wrapper from the menu. So the default is to perform the new access-checking but still retain the older, unwrapped html structure, and avoid messing up anyone's existing  listviews etc.

Example:

```
drupalgap.settings.menus['main_menu'] = {
  options: {
    attributes: {
      'data-role': 'listview'
    },
    wrap: true
  }
```

Pull request sent.

I'm not so sure about the navbar() call, it seems to me that other JQM widgets may possibly be affected by the deferred creation. If so, I guess that's a new issue anyway.

**Comment by signalpoint** [comment]
@johnpitcairn thanks! I ran into this exact same issue today, and your fix worked great. I'll be merging it back into 7.x-1.x shortly.

**Comment by signalpoint** [comment]
Also see here for a new age workaround: http://www.drupalgap.org/node/518
