### ISSUE TITLE
drupalgap text field problem

### ISSUE THREAD

**Issue by sperlari** [signalpoint/DrupalGap#269]
I have a problem with fields in my app...I set correctly the display settings of content in my drupal site but nothing...drupalgap doesn't return me data. It returns only titles of fields. I have installed modules for drupalgap...nothing.
What Am I Doing Wrong?

**Comment by signalpoint** [comment]
@spexy90 A few things...

Did you replace index.html with the contents of ripple.index.html? I say this because it appears your app is trying to load cordova.js, which is not needed when inside of Ripple.

The lightbox module doesn't exist yet, so that field definitely won't work.

As for the date field...

```
date_field_formatter_view - unsupported type (date_plain) 
```

The date module would need to be expanded to support date_plain.

As for fivestar, you need to enable the fivestar service resources under Structure -> Services -> drupalgap

Have you updated the bin/drupalgap.js file to the latest development snapshot?

**Comment by sperlari** [comment]
I know the problem with ripple but I have replaced index.html whit the contents of ripple.index.html...I don't understand. 

Ok, I'm trying to set services settings and now my app (localhost) returns me data. Now my problem is in services settings.. i don't see fivestar and data in services module in my drupal site and taxonomy in my app returns me the number of term, not the term...i have installed modules for drupalgap in localhost...the problem is in my site? Thanks for the help you're giving me!

**Comment by signalpoint** [comment]
@spexy90 

`
The lightbox module doesn't exist yet, so that field definitely won't work. You can create it if you want and be the maintainer, I'm sure it will be almost identical to the colorbox module for DrupalGap.
`

If you don't see Fivestar services on your site, then you didn't install the companion module for it. Follow the instrucitons here:

http://drupalgap.org/project/fivestar

You need to install that sandbox module.

As for the term ids, you need to grab the development snapshot of the DrupalGap module.

**Comment by sperlari** [comment]
As for the term ids, you need to grab the development snapshot of the DrupalGap module.  I don't understand..sorry

**Comment by signalpoint** [comment]
@spexy90 Download the development snapshot of the DrupalGap module, and replace the existing DrupalGap module on your Drupal site with it:

http://drupalgap.org/download

**Comment by sperlari** [comment]
mmh ok, it works now!...i see number only for hierarchical select result. Thanks for the help!
