### ISSUE TITLE
back button / cache

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#32]
When I navigate between content lists and nodes, the back button doesn't seem to work. I'm solving this with caching here and there. I know this is a bit of a jquerymobile issue. Just wondering if you have an approach that works well navigating from a list to a node and then back.

**Comment by signalpoint** [comment]
Do you mean the actual back button on an Android device, or some of the back buttons that are on display via jQM?

**Comment by chrisschaub** [comment]
Ok, after a few days of tinkering, I think I have some insight here. The way the drupalgap pages/scripts are broken out with pageshow (and other events) causes issues with the back button, the JQM back button. It's actually a JQM problem in some ways, but the default app could be re-organized a bit to help out.
1. If you navigate to a node, the node.nid is stored in an object to be used by node.js. But if you click on a node from that page, then hit the back button, pageshow will not fire. This is a JQM thing, lots of mentions about this. I got around this by moving all "scripts" to a standard include js file that gets loaded when the app first starts via index.html. 
2. Related to #1, pageshow, pageinit events will run multiple times in some scenarios if the script files are added at the "page" level, when JQM changes the pages. Moving the pageshow, pageinit handlers to a single file(s) that gets included when the app starts solves this.

I think this style of JQM event handling is better:

$(document).on('pageshow', 'div:jqmData(role="page"), div:jqmData(role="dialog")', function(event){
  switch(event.currentTarget.id) {
  ...

It binds more tightly IMO and allows you to switch on the page that just loaded.

This is further complicated because the node.html page has ever changing content depending on the nid that comes in. I think it's better to use this url format in the content lists:

node.html?nid=123456

So that you can just parse the querystring to get the nid. This will always work, even with the back button. Caching the nid in the drupalgap object is problematic.

Ok, these are just my observations, and again, thanks for all of your hard work! Btw, we've met before at UofM when I worked there.

**Comment by signalpoint** [comment]
Hey, thanks so much for all of the debug information. I've been trying to find a more dynamic way around this hole dilemma since late November, and something really solid is coming forth in the Alpha version that should solve many of the issues you've described here.

In regards to your comments:
1. The upcoming Alpha release has done away with the setting of the global drupalgap.node.nid and drupalgap.node_edit.nid. It is all being replaced by hook_menu style dynamic paths like node/123, user/456.
2. This is great information. I've often wondered why these events get fired multiple times on some occasions and not others. Again, I think the Alpha release will have this covered as there are no longer dozens and dozens of pagebeforeshow and pageshow handlers.

If you wouldn't mind branching DrupalGap here on GitHub, I'd like to keep an eye on your improvements. I am particular curious about your code snippet above and how it is being used.

As for the node.html?nid=123 idea, thank you. I decided to fall back on what we know best, and that is Drupal paths! So in the upcoming Alpha we'll have paths like node/123, etc, as mentioned earlier. You are right, the caching of ids in the drupalgap object was/is a bad idea, and needs to go away!

Thanks again for the insight, I look forward to seeing some of your code!

P.S. Hey Chris! That's where I recognized your screen name on GitHub, from UM, haha! Thanks again for recommending me for the BMC2 position. You had asked me a very important question at the end of the interview, and that was along the lines of "Do you think you would enjoy this work?".... and I thought about that more and more, and think the Library is a much better fit. I hope all is well in Tennessee!

**Comment by signalpoint** [comment]
This issue should be all wrapped up now that we are using a node/123 path system, upgrade to the latest Alpha for fix. Please feel free to re-open if problems persist.

**Comment by signalpoint** [comment]
This should be resolved now with the commit mentioned above.
