### ISSUE TITLE
Cannot fire Drupalgap in xCode and iOS simulator

### ISSUE THREAD

**Issue by mfuggle** [signalpoint/DrupalGap#329]
I have Drupalgap functioning on a remote website in the Ripple Emulator, however when I try to get it functioning in xCode using the iOS Simulator I have been unsuccessful. The attached image shows that Cordova is running successfully but I have been unable to get DrupalGap to fire up. I have checked settings.js and built the environment from the documentation three or four times but I cannot see what's causing it to fail.

Help would be much appreciated.
Martin Fuggle
![apache cordova issue](https://cloud.githubusercontent.com/assets/1777429/3888409/847f08ec-21ff-11e4-8ce1-98449a85add5.jpg)

**Comment by signalpoint** [comment]
@mfuggle Have you installed the plugins? Step #4 here: http://drupalgap.org/node/193

Either way, try modifying drupalgap_onload() in src/drupalgap.js then running the makefile: http://drupalgap.org/node/224 (or you can modify the bin/drupalgap.js file directly).

What I recommend is placing a console.log() message each step of the way through that function, and see what code (if any) is being called. Then rebuild/prepare the app for iOS from the terminal, then run it again and watch the console.log() messages in xCode.

Please report back here how far along in the drupalgap_onload() function the app makes it. Don't forget to set drupalgap.settings.debug to true (near the bottom of the settings.js file)

**Comment by mfuggle** [comment]
I have set console log messages at various points in drupalgap.js but it doesn't appear to invoke the drupalgap.js file. What causes the invocation of the drupalgap.js file? That just doesn't appear to get started.

**Comment by signalpoint** [comment]
@mfuggle The whole process starts with...

```
drupalgap_onload();
```

which attaches PhoneGap's device ready listener...

```
// Add PhoneGap's deviceready listener.
document.addEventListener('deviceready', _drupalgap_deviceready, false);
```

Try placing some console.log() messages in the drupalgap_onload() function.

Please confirm wether or not you are editing files in the src/ directory. If you are, the bin/drupalgap.js file needs to be regenerated using the makefil. Otherwise you can edit the bin/drupalgap.js file directly.

Either way, what version of PhoneGap are you using? Maybe they have changed the way the deviceready event takes place.

**Comment by mfuggle** [comment]
I am using Cordova version 3.5.0-0.2.6. There is already a console.log( ) command inside the drupalgap.onload function and I have inserted others at various points. The index.html clearly calls drupalgap.onload as its last instruction but I still only get Apache Cordova Device Ready on the simulator and no console log messages are displayed.

It all looks OK to me but clearly there is something going on here that has escaped me. Would it be better if I pay you for an hour to have a look and see if there is something obvious that I am missing?

**Comment by signalpoint** [comment]
@mfuggle - Looks like this message from you was cutoff, I am placing it here for reference:

```
Further to the above. When I try to set up the environment to generate the drupalgap.js file I get the following errors:
brew install unzip - No available formula for unzip
sudo make -B tools - No rule to make target 'tools'
```

That would be great if you'd like to purchase an hour of premium support, that can be done here: http://easystreet3.com/purchase-time

I am guessing it has something to do with Cordova 3.5, I've only made it to testing/debugging 3.3 on iOS. I primarily deal with Ripple, and Android, but have the resources to develop for iOS as well.

As for the makefile, I've only ever ran it in Linux, and I know others have had problems on a Mac. We either need a separate makefile for Macs, or if someone with makefile skills could step forth and figure out the equivalent for Mac ;)

UPDATE: Regarding the makefile, I see you've placed the resolution for your issue here: http://drupalgap.org/comment/120#comment-120

Thank you for following up.

**Comment by mfuggle** [comment]
WRT the cut off message - initially I had trouble getting unzip installed and also the $ sudo make -B 'tools' command but eventually got those resolved. However the issue remains as reported and that is that I only get as far as the Apache Device Ready display. Unfortunately I don't have the skills to go further so I guess I am now stymied unless you can suggest a course of action to get the matter resolved on the Mac.

Cheers - Martin Fuggle

**Comment by signalpoint** [comment]
@mfuggle Thanks for the follow up, and for your debugging of the makefile.

It will be a few more weeks until I need to pull out the Mac and do a fresh install, at that time I'll be trying version 3.5 of PhoneGap/Cordova.

If you need immediate support, I'm available for premium support, thanks!

**Comment by mfuggle** [comment]
Thanks for that. I'll keep the Mac environment in place but install a Linux VM and have a go with Linux.

**Comment by signalpoint** [comment]
@mfuggle Check out this issue, it may be related: https://github.com/signalpoint/DrupalGap/issues/370

Essentially it sounds like you may have to remove the line of code that includes the `cordova.js` file in your `index.html file` on a Mac/xCode/iOS-Simulator.
