### ISSUE TITLE
entity.load(node) - only single ids supported

### ISSUE THREAD

**Issue by mfuggle** [signalpoint/DrupalGap#378]
I have created a list of nodes (articles) using Views Render Arrays. When I click on one of the entries to display the details of the node I get an error:

entity.load(node) - only single ids supported

I have tried to find the cause but have failed. There was a previous post on this subject which has been closed but it did not seem to provide a solution to the problem.

**Comment by mfuggle** [comment]
I have solved this. The nid must be the first entry in the list of fields in the view and have no label associated with it. At least that's what solved the issue for me.

**Comment by signalpoint** [comment]
@mfuggle Pretty close. The node id can be anywhere in the field list, but it is good practice to set the label on the node id field to `nid` (or as you saw, using no label at all results in the property name being `nid` in the JSON).

For others, whenever you see this error, 99% of the time it means the link you are building to your node, e.g. `node/123` is broken, e.g. `node/undefined`. Check your JSON results and make sure you know what property name you are trying to extract the node id from. A common mistake is having the label set to `Nid` instead of an all lower case `nid`.

**Comment by chrisschaub** [comment]
Hmm, seeing this as well. I definitely am passing node/### to drupalgap_goto. Sort of happens randomly. Trying to track it down.

**Comment by signalpoint** [comment]
@chrisschaub It can happen elsewhere too, it primarily means someone is calling some type of entity `*_load()` function and passing a non number value to it.

**Comment by chrisschaub** [comment]
Ok, I am not doing any type of entity_load or custom entity loading that is non-numeric. I only do a node_load and taxonomy term load, and i'm doing an is_int. I'll bet there's something else going on here. It could be that I'm using a panel for navigation -- I've seen clicks bleed through to other selectors. But I am preventing default on all panel clicks anyway just to be sure. Still a mystery.

**Comment by chrisschaub** [comment]
I think there is more going on here. I mostly see calls for node/745 type
URLs. But randomly, the URL is passed as node_745 ... and I can't find  a
place where I'm doing that.

**Comment by signalpoint** [comment]
@chrisschaub Interesting. The `node_745` syntax would be identical to the `id` that is attached to the node's page container `div`. Perhaps some code (custom, other) is trying to grab the page id (for some reason) and use that to try and load a node?? I don't recall implementing anything like that.

However, I recently changed the routing of node/%/view to go to node/% automatically to help with local tasks: #279 

Before that commit, I believe the page ids for nodes followed this pattern, e.g. `node_745_view`, instead of the new `node_745`. Maybe that is confusing some code out there.
