### ISSUE TITLE
jQM Multi-Page vs. Single Page

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#49]
An excellent question from @scotthooker via e-mail, it deserves an issue discussion here:

"Looking into the paging issue. Was your original intention for the pages to be loaded as a JQM multi page step. I.e. they are stacked with "data-role" pages or did you intended for them to be a single page where the content region gets replaced?"

**Comment by signalpoint** [comment]
Hi Scott,

My original intention was for the jQM multi page setup, i.e. each time you navigate around, a new div with a data-role="page" is generated. Any time you navigate back to page that is already in the DOM, it will remove it (I think there is a bug with this though and it doesn't actually remove it) then rebuild the page and add it to the DOM. Now that I think about it, that approach may be bad for performance (i.e. removing the page and rebuilding it). But I think my original intentions were because of the dynamic nature of the pages (i.e. stuff needs to be fetched from Drupal), the pages were to be rebuilt each time.

I'm open to the "singe page" approach. I'd love to see some benchmark stats comparing both approaches, but I'm not sure how to measure it.

Just last night I was thinking that drupalgap_goto should be modified to as quickly as possible built an empty page, toss it onto the DOM, navigate to the page, then let something like jQM's pageshow event take care of all of the heaving lifting, that way the navigation around will be quicker (I'm not sure if it actually will be quicker though).

Either way, I'd love to hear more thoughts on this and any ideas on how this very important feature can be improved!

**Comment by scotthooker** [comment]
Thanks!

I'm not sure I fully understand either the intention of DrupalGap or the intention of JQM.

What I see in the DOM when I navigate to a new page is <div id="page_id"> lots of stuff </div> 

However, the old page also gets left in the DOM which from what I'm trying to do is bad news. It means when I come back to the page it already exists and for some reason or another any events no longer get run. 

For example I have a view on my homepage that I'm reading out then writing the content into the page. Works fine when the app loads. However, once I navigate off to a different page then page to the homepage the content doesn't get written into the page. Very strange. I see that as the major bug to any approach as it stops any of the drupal functionality working as I can't get stuff and write it into the page the 2nd time round.

Some other things I've noticed that I don't understand 
1. Why is the whole page being generated and not just the content region? I.e. I end up with lots of "navigation" blocks in the dom as each page has one. Rather than them remaining on the page but the inner content region changing.

---

HOWEVER In answer to the above. The way I would recommend, or think it should work due to the fact we are a drupal site and want to load dynamic content for the most part. Therefore we should act like drupal. The best fitting part of this is JGM multipage. I think what drupalgap so far has done is try to merge the two concepts by attempting to leave content in the dom once its visited. 

Therefore I propose the following when you click a drupal_goto link we navigate to the new page and remove the old page.

**Comment by scotthooker** [comment]
Also, you are right there is a bug the page doesn't get removed. And if you do remove it I end up with all sorts of undefined errors which I can't see to debug properly.

**Comment by signalpoint** [comment]
The intention of DrupalGap is to utilize Drupal concepts for building mobile apps (i.e. menus, blocks, regions, themes, modules, users, etc). It also aims to provide an API to communicate with Drupal websites.

The intention of jQM is really only to provide an easy way to make the app look like a mobile app. Without, plain old html (and my css skills) look pretty boring. Over time though, jQM has proved useful with the way(s) it handles pages, and also for its page events (pagebeforeshow, pageshow, etc).

I hope that clarifies the intentions of DrupalGap, if not please let me know any other questions.

I agree, leaving the old page in the DOM is no good, and I've experienced the same problems you describe when navigating back to a page that was previously visited. So I can see why the 2nd visit to the page isn't being populated, because it probably populating the first page (still in the DOM and not visible). A bad bug indeed, I created an issue for it:

https://github.com/signalpoint/DrupalGap/issues/50

Will you please review my description of the bug and add any additional information that would be helpful?

As for the "whole page being generated"... this was because each page has regions, each region has blocks, each block has visibility rules that can be different depending on the current page or user roles of the current, so (at the time of implementation) it made sense to re-draw the data-role page div each time, that way the regions/blocks could be generated accordingly.

**Comment by scotthooker** [comment]
Gotcha re: drupalgap. Makes perfect sense and a brilliant addition. I certainly have enjoyed using it so far!

I've replied to the issue :) I actually think its a timing issue for when the old page gets removed. It happens after the new page is loaded. It should probably happen before.

I agree on the whole page. I thought that would be the case. Makes perfect sense.

**Comment by signalpoint** [comment]
In conclusion, we'll leave DrupalGap as a jQM multi-page implementation, and #50 will handle the remaining bug(s) mentioned.

Feel free to re-open any time if new thoughts arise on using jQM's page system(s), thanks!
