### ISSUE TITLE
CSRF validation failed

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#53]
Since Services 3.4, any calls via POST, PUT or DELETE need a CSRF token header sent along.

https://drupal.org/node/2013781

**Comment by signalpoint** [comment]
I'm not convinced this is solved yet, we're still getting bug reports. Probably related - https://drupal.org/node/2020417

**Comment by ghost** [comment]
Any update on this issue?

**Comment by signalpoint** [comment]
@botty - is there a particular Service Resource that you are getting this CSRF validation failure? The latest alpha snapshot on github defitely has some progress on this issue, it seems the only remaining issue is with login/logout when developing inside of Ripple. Will you please describe your issue in more detail? i.e. Are you developing for Android, or iOS? Inside an emulator, or compiling directly to a device? Developing in Ripple?

**Comment by ghost** [comment]
Hi Tyler

I've updated to DrupalGap-7.x-1.x-alpha and it seems to have removed the CSRF issue, I am however getting a new error.created new issue here https://github.com/signalpoint/DrupalGap/issues/67

(via Xcode 4.6.3 and running on iPhone 4S -  Cordova 2.7.0 - not using ripple)

**Comment by signalpoint** [comment]
Closing this issue. The work around to be able to develop in Chrome with Ripple is to install DrupalGap within the same domain as your Drupal site. For example, if your Drupal site is available at example.com, then install DrupalGap at example.com/mobile-application as the place to run the app. No need to disable web securtiy. For more information, see the Ripple guide: http://drupalgap.org/node/103

**Comment by x7ian** [comment]
Hello,
Ive installed Drupal 7 and the module drupal gap and generated and launched the app. 
It seems to be working ok. I can login with any created user.
However when i go to user register form and create a new account, when i submit the form, it gives me the account created alert message saying "Registration Complete!".
However after that it gives me a second alert saying that "CSRF validation failed".
Then after that If i refresh the page/app, the new user is logged in. If i logout and go to the login form and login again it works perfectly.
The CSRF error shows up only when creating a new account. 
What i want is for the user to be logged in automatically when the account is created.
I installed Login Toboggan in Drupal and Drupalgap, and configured it so that the user will be logged in inmediatelly.
Im working everything on localhost.
Ive tested on poster my url:
http://localhost/sandbox.codeatrium/?q=drupalgap/system/connect.json
it show the "CSRF validation failed" error.
I dont understand why is it that this only happends when registering a new account and the normal login works fine.
Any sugestions on why could it be that this is happening!
Thank you for your help!
