### ISSUE TITLE
jQM pageshow callbacks defined in hook_menu called twice

### ISSUE THREAD

**Issue by signalpoint** [signalpoint/DrupalGap#54]
It appears any jQM pageshow callbacks defined by hook_menu are called twice. For example, the node_page_pageshow() seems to get called twice, just place an alert in the 'success' callback to see the behavior.

**Comment by chrisschaub** [comment]
I've been trying to track this down. I think the issue is

``` javascript
// TODO - why are these jQM page events being called more than once?
var script_code = '<script type="text/javascript">$("#' + page_id + '").on("' + jqm_page_event + '", ' + jqm_page_event_callback + ');</script>';
```

in menu.js.

Most of the pageshow stuff has already been loaded via the head tag, runs once. This code above gets injected into every jqm "page". My experience is that this will cause the event to fire twice, or appear to. This is similar to the issue in the past codebase where the code was broken into multiple files, loaded at run-time. This caused events to fire twice, especially with the back button.

**Comment by chrisschaub** [comment]
I think this bug gets at it:

http://bugs.jquery.com/ticket/10168

It seems that inline event handlers can cause double firing. Now, not sure this applies to pageshow, but I'm betting. I've just seen this happen a lot with jquerymobile and inline event handlers. I can't think of a better way to do it, though.

**Comment by signalpoint** [comment]
FYI, since we use inline JS to attach these jQM page events, they are still firing (or appear to fire multiple times). We added drupalgap_jqm_page_event_fire() to prevent page event handler functions from being fired multiple times, even though the jQM event itself gets triggered multiple times.
