### ISSUE TITLE
cannot render image on mobile app

### ISSUE THREAD

**Issue by Sunia88** [signalpoint/DrupalGap#581]
although i put the image on sites/default/files/, mobile app can't render it, but web app and ripple can render it

**Comment by Sunia88** [comment]
mobile app can't render it like there is a wrong path image

**Comment by d0t101101** [comment]
Hi,

I hit this too when developing a custom module.  Seems the relative paths vary depending on how you are viewing the app (i.e. phonegap vs web-app in settings.js), and possibly some other cases too.  My workaround was to specify the full path to the image, like so (in one of my js functions), using a DrupalGap variable defined in settings.js:

`<img src="' + Drupal.settings.site_path + '/sites/default/files/styles/slideshow/my_image.png"></img>`

Hope this helps!
.

**Comment by Sunia88** [comment]
Yess you right, it's work, thank you

**Comment by ReisQuarteu** [comment]
Hi.

I can't render the images from my Drupal web site's nodes either on my mobile app.

I've tried to define the public files with an absolute URL (Drupal.settings.file_public_path = 'http://www.mywebsite.com/sites/default/files';) in the settings.js file, but it didn't work either.

Am I doing something wrong? Or is there something I should have done before?

Any help will be greatlt appreciated.
Many thanks in advance! :)

**Comment by ReisQuarteu** [comment]
I've just found out why the images from my Drupal web site's nodes weren't rendered on my mobile app.

When an image is placed on the HTML of a node, its src atrribute reads "/sites/default/files/image-name.jpg|png|gif". When the HTML node is compiled into the app, that src means nothing, because it's absolute to the web site, but on the app there is no web site...

So the solution is to update the node's HTML, changing the src attribute of the image I want to be rendered by the app to somthing like this: "http://www.mywebsite.com/sites/default/files/image-name.jpg|png|gif".

I hope this can help someone out there who has been banging his/her head onto the table for quite a long time...

Best regards to all! :)

**Comment by signalpoint** [comment]
@ReisQuarteu Yes, that is the best way to fix this problem, by making the src of the image absolute in the node's html. There's also a helper sandbox module for this: https://www.drupal.org/sandbox/signalpoint/2068317 - I've been meaning to promote that to a full project because it is pretty useful.

**Comment by ReisQuarteu** [comment]
It's the way to get things working with Drupalgap, but it's not the best way to work in Drupal, because you lack the flexibility to move your web sites to another locations: your HTML code will simply break.

It would also be a good idea if Drupalgap could change the Drupal nodes' HTML code so that all URLs become absolute. Is it necessary to create a new Drupalgap module to achieve this functionality, or is there a more suitable module where we could make such changes?

Thanks in advance! :)

**Comment by signalpoint** [comment]
@ReisQuarteu  The Pathfix Sandbox module linked above is the best solution.
