### ISSUE TITLE
React instead of Angular?

### ISSUE THREAD

**Issue by coolman7** [signalpoint/DrupalGap#625]
React is getting stronger and widely used. While changing framework, is it better to switch React instead of Angular?

**Comment by signalpoint** [comment]
@coolman7 This was a primarily a decision I made based on a lengthy BOF in DrupalCon Los Angeles about Headless Drupal. The general consensus seemed to be that Angular is awesome, and that's why I rolled with it.

At this point I've sunk too many resources into Angular to turn back, plus I think Google based technologies are far superior to Facebook based technologies. Not enough folks stepped forward and expressed pros/cons for this decision, so I went with what I felt was best.

**Comment by signalpoint** [comment]
DrupalGap 8 is completely headless, and will be pure JavaScript. I hope to backport it has a 7.x-2.x branch.
