### ISSUE TITLE
Page Titles

### ISSUE THREAD

**Issue by chrisschaub** [signalpoint/DrupalGap#63]
I think the page titles are not working after the latest pull of alpha, last night. I think it's related to pageshow. I have a menu path that calls a pageshow function for that path. The title never gets set.

And when I try to:

$('.ui-page-active .ui-header h1').html('The Foo');

it doesn't work. I think it's because, when I alert the current value of H1 within pageshow, it shows the previous page's value. I'm still digging but it broke right after I pulled.

**Comment by signalpoint** [comment]
That's cool that you had page titles working, I don't think they have ever worked? Have they? Or were you using that custom snippet above to make it work?

As for the previous page being caught by the selector, I've learned that in order to transition to another page, one page still has to be in the DOM. I'll dig a bit deeper into page titles and see what's happening. Any additional info is greatly appreciated.

**Comment by signalpoint** [comment]
You should no longer need the jQuery snippet mentioned above. The header block is now automatically set with the page title defined by the active hook_menu() menu link item.

**Comment by chrisschaub** [comment]
Awesome!
