### ISSUE TITLE
How to get user field values?

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#641]
I created a field call `field_open_inappbrowser` for user accounts. I have two values, 0|No and 1|Yes, for users to select whether to open links within the app or with the system browser. Before I build a link, I want to get the field value for that particular user. How do I get the value of the field?

I tried `console.log(Drupal.user)` to see if I can see the field, but don't see it.

**Comment by signalpoint** [comment]
@mkinnan The `Drupal.user` object probably doesn't contain the fully loaded user. You could post process the system connect call, and do a `user_load(Drupal.user.uid)`, and then in its success callback set Drupal.user equal to the result. http://api.drupalgap.org/global.html#hook_services_postprocess - this would be done client side (in the app), and would require one extra call to the server.

I guess the preferred way would be to do it server side using hook_services_request_postprocess_alter() : http://cgit.drupalcode.org/services/tree/docs/services.alter.api.php - it would be similar in that you'll intercept the system connect, then replace the user object contained within that result with a full user load. This method would then allow `Drupal.user` to be auto populated in the app, without any extra server calls.

Without the full user load, I don't think any custom fields are included, this is by design in Drupal core.

**Comment by signalpoint** [comment]
To follow up, this was the solution @mkinnan and I arrived at:

```
/**
 * Implements hook_services_request_postprocess_alter().
 */
function my_module_services_request_postprocess_alter($controller, $args, &$result) {
  if ($controller['callback'] == '_system_resource_connect') {
    global $user;
    if ($user->uid) {
      $account = user_load($user->uid);
      unset($account->pass);
      $result->user = $account;
    }
  }
}
```

Add this to your my_module.module file up in Drupal to have a fully loaded Drupal.user object available to you in DrupalGap.

**Comment by jomarocas** [comment]
@signalpoint thanks is usefully

**Comment by gs9999** [comment]
in the above code, which I implemented and I confirm works, how do I replace, 

_system_resource_connect

to be the system rest call for a user_load().  I want to include profile2 fields into my loaded user object. 
This uses a separate drupal function to load them.  I already got it working in the Drupal.user. object., but I want to be able to load them for individual users on demand.

Thanks

**Comment by signalpoint** [comment]
@gs9999 I recently took a similar approach to what's listed above, except used it during the `_user_resource_retrieve` callback:

```
/**
 * Implements hook_services_request_postprocess_alter().
 */
function my_module_services_request_postprocess_alter($controller, $args, &$result) {
  if ($controller['callback'] == '_user_resource_retrieve') {
    $result->my_module = array('foo' => 'bar');
  }
}
```

Then in DrupalGap, when you have a fully loaded `account` object via `user_load()`, your custom data will be available:

`console.log(account.my_module.foo);`

**Comment by gs9999** [comment]
@signalpoint what is the user id (uid) location in the $controller[] object?, or the $args object,.. I've been trying to find out exactly where the uid is, but no luck so far.

**Comment by signalpoint** [comment]
It's in $result->uid
- Tyler (sent from mobile device)

**Comment by gs9999** [comment]
Aloha Tyler,

Can this method be used, alternatively, on the user_update call?  I.e. what I'm going after is a creating a custom form, and then at the end using user_update(), then edit the callback in PHP (drupal site) to be able to handle the fields passed using user_update()  and populate them in their appropriate fields and such.  Can this be done this way?

Thanks, 
GS

**Comment by signalpoint** [comment]
@gs9999 I would just create a custom service resource with arguments, then have my DG form submit those values to the custom resource, then let PHP handle the user_save(). http://docs.drupalgap.org/7/Services/Create_a_Custom_Service/Custom_Service_Resource_with_Arguments
