### ISSUE TITLE
how to alter values of a content type before display

### ISSUE THREAD

**Issue by days4** [signalpoint/DrupalGap#645]
Hi,
I am working on a project in that there is a multivalued field changed using hook_node_view .
So when i am accessing that content in drupalgap app it's different than the site. To display the Content as on the site i wrote a custom function to retrieve the values .I am able to get the values but don't know how to alter the field before display in app. As this is multivalued test field so it's formatter is already written.

**Comment by signalpoint** [comment]
@days4 DrupalGap will not be aware of any implementations of `hook_node_view()` on your Drupal site, because nodes are always delivered to DrupalGap as JSON, and then rendered client side. For altering node content in DrupalGap, these 3 hooks may be of use:
- http://api.drupalgap.org/global.html#hook_entity_post_render_content
- http://api.drupalgap.org/global.html#hook_entity_post_render_field
- http://api.drupalgap.org/global.html#hook_node_page_view_alter_TYPE

**Comment by days4** [comment]
thanx @signalpoint for your help i now i am able yo alter the content and display it.
