### ISSUE TITLE
Location field shows null on node page in app

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#656]
Drupal:
Drupal core 7.41
Location 7.x-3.7
DrupalGap 7.x-1.13+11-dev (2015-Oct-27)

Drupalgap:
Using SDK from 2 weeks ago ...
most recent location module

In Drupal, I have enabled the location and location cck modules that are part of location. I am not using node locations module, only the field one. I then added a field to my node. In the Drupalgap app, it still displays null. Here are the console.log error messages:

`WARNING: _drupalgap_form_render_element() - location_cck_field_widget_form() does not exist for the "location" form element!`
`WARNING: _drupalgap_form_render_element_item() - Field undefined not supported.`

**Comment by signalpoint** [comment]
@mkinnan The missing `location_cck_field_widget_form()` would control the add/edit form for the node. It's been over a year since I implemented `location_cck_field_formatter_view` which is in charge of displaying the field when someone is viewing the node in the app. The first would definitely need to be implemented, and the latter may need some adjustments since it's been almost 1.5 years since its update. I personally use the address field module, which has much better support in DG. But I know location is popular, and I'm open to supporting it, but I don't use it ATM.

**Comment by mkinnan** [comment]
Thanks Tyler. I will take a look at address field module to see if it does everything i need. One thing convenient with location module is that it auto creates a google maps URL, which should open in google maps app.

**Comment by mkinnan** [comment]
Address Field Module has been working great. Creating Google Maps URL was easy by creating a separate link field on my website, and then a rule to automatically generate the URL and populate in the link field. Then it gets displayed as a button link.
