### ISSUE TITLE
Logout bug

### ISSUE THREAD

**Issue by ntym4ek** [signalpoint/DrupalGap#680]
I have the same issue as https://github.com/signalpoint/DrupalGap/issues/621
To reproduce bug:
1. Clean install of latest 1.3 Mobile Application Development Kit and var setting in settings.js (only Drupal.settings.site_path).
2. Login with application.
3. Logout same way.
4. Click user icon
![1](https://cloud.githubusercontent.com/assets/11538342/11657919/d36174b0-9dd0-11e5-9070-37f5b752e284.jpg)

**Comment by signalpoint** [comment]
@ntym4ek Please use FireFox Poster (or Chrome POSTman) to manually login/logout of your Drupal site. More info: http://tylerfrankenstein.com/user/4/code/drupal-services-examples

If you are able to successfully login and logout with those plugins, then it is a DrupalGap problem. Please confirm.

**Comment by ntym4ek** [comment]
Chrome POSTman login was successful 
...
"user": {
     "uid": "2737", 
...

Problem is not with login.
After I login by application, I have access to user's account, it's ok here.
Issue appears after logout. I click Logout, page refreshes and then, when i click User button (top right corner) - menu panel and message appears - you can see it at screenshot.
So, user is logged out, but menu shown for logged in user. And that message pops up.

Described problem appears if I do actions successively, one by one: open app page - login - logout.

If I do it in next order: open app page - login - refresh page - logout, problem does not appear, user menu shown for logged out user, message does not pops up.

As described in https://github.com/signalpoint/DrupalGap/issues/621 looks like problem is in drupalgap_remove_page_from_dom function. Read that issue too, plz.

Just now reproduced this bug at http://demo.drupalgap.org/mobile-application, it's right as I described.

**Comment by Digeridoo** [comment]
@signalpoint I confirm the issue. To fix it just add `{reloadPage: true}` to **drupalgap_goto** call in **user_logout_pagechange**. See: http://grabilla.com/0621b-adb6c98f-bfb6-4ce7-9e25-57319ea23e74.png

**Comment by Digeridoo** [comment]
Also, I suppose that `{reloadPage: true}` should be added to call of **drupalgap_goto** in user login/register success callback too.

**Comment by signalpoint** [comment]
@Digeridoo Will you please submit a pull request with the `reloadPage` fix you describe? It'd be great to get you credit for the fix, thank you!

**Comment by Digeridoo** [comment]
@signalpoint thanks for a proposition. But it is quite time-consuming to commit changes only in 3 lines by using pull requiest. You can use my idea of hotfix without any problems and questions.

Please note - it is just a hotfix. The problem is a little bit bigger. Option `{reloadPage: true}` in menu does not work as expected. It only reloads pages which
- already exists in a dom
- menu item of this page (destination) has option `{reloadPage: true}`

So this option in menu does not influence on a **drupalgap_goto** as expected (it does not replace option `{reloadPage: true}` directly on **drupalgap_goto**). In this case the full fix will be (one of)
- add option `{reloadPage: true}` to all important calls of **drupalgap_goto**
- change behaviour of menu item option `{reloadPage: true}` using with **drupalgap_goto** (i.e get option from current path menu item and not from destination, but it will influence on other pages)

**Comment by Digeridoo** [comment]
@signalpoint thanks, but it does not work. A proper hotfix will be to set `{reloadPage: true}` on **drupalgap_goto** calls on logout/login callbacks (see #732 too). Or see other ways below.

The problem is bigger then it looks. Main problem that **drupalgap_remove_pages_from_dom**, actualy, does not remove page from dom, but clears all internal variables - http://grabilla.com/0621c-0de4d9b1-a9fa-4bcb-8871-915f4bc699de.png. While **drupalgap_page_in_dom** checks pages exactly in dom and not in internal variables - http://grabilla.com/0621c-83db4775-d586-45e0-9e42-8075dfd63a36.png. This is why you can do **drupalgap_remove_pages_from_dom** as many times as you want, but **drupalgap_page_in_dom** will always return true. This breaks **drupalgap_goto** functionality and page continue loads from dom without reloading. Please, see my debug with comments - http://grabilla.com/0621c-93559127-a369-4c1f-8ceb-2f69a52b777e.png

I can see here several ways
1. fix **drupalgap_remove_pages_from_dom** or **drupalgap_page_in_dom** to use one logic for both functions.
2. use `{reloadPage: true}` on **drupalgap_goto** - all important calls (logout/login/register/etc)
3. use menu item option `{reloadPage: true}` of both paths in **drupalgap_goto** - source (current page) and destination page. Or add a new option to menu like gotoReloadPage (it means that all gotos from this page will be called with `{reloadPage: true}`). Actually, in **drupalgap_goto** reloadPage used only from destination page - http://grabilla.com/0621c-b0cfc95d-4b46-4a01-a469-8d628df72251.png

**Comment by Digeridoo** [comment]
Also, point 3 can be done as a new functionality. It can be usefull to force target page to reload.

**Comment by Digeridoo** [comment]
Additionaly, in the code we have two functions with the same name - **drupalgap_remove_page_from_dom** (src/drupalgap.js - http://grabilla.com/0621c-192d35ff-b307-408e-aac6-1a93e5e5ddd0.png and src/includes/page.inc.js http://grabilla.com/0621c-9f1f4023-0504-494c-8c5d-8476fa5f01db.png).

Thanks to @mkinnan comment [here](https://github.com/signalpoint/DrupalGap/issues/621#issuecomment-137958248)

**Comment by Digeridoo** [comment]
Final fix

```
diff --git a/mobile-application/src/includes/page.inc.js b/mobile-application/src/includes/page.inc.js
index dcb9766..0f0a736 100644
--- a/mobile-application/src/includes/page.inc.js
+++ b/mobile-application/src/includes/page.inc.js
@@ -266,9 +266,10 @@
 function drupalgap_remove_pages_from_dom() {
   try {
     var current_page_id = drupalgap_get_page_id(drupalgap_path_get());
-    for (var index in drupalgap.pages) {
-        if (!drupalgap.pages.hasOwnProperty(index)) { continue; }
-        var page_id = drupalgap.pages[index];
+    var pages = drupalgap.pages.slice(0);
+    for (var index in pages) {
+        if (!pages.hasOwnProperty(index)) { continue; }
+        var page_id = pages[index];
         if (current_page_id != page_id) {
           drupalgap_remove_page_from_dom(page_id, null, current_page_id);
         }

```

**Comment by signalpoint** [comment]
@Digeridoo thank you for your detailed description of the issue at hand. I think we've got this all sorted out now, grab the latest bin/drupalgap.js or min.js for the fix(es). With @ahmedbarwary , we opted for no. 2 that you mentioned above.

As for `drupalgap_remove_pages_from_dom()`, it will remove all the pages from the DOM, except the current one, because AFAIK jQuery Mobile needs at least one page in the DOM to properly transition to the next page, so that is why we always leave the current page in the DOM.

I personally think `drupalgap_remove_page_from_dom` and `drupalgap_remove_pages_from_dom` are both abstracted and re-using eachother as much as possible already, but I'm definitely open to pull requests and any suggestions/improvements.

**Comment by Digeridoo** [comment]
@signalpoint lets try again. What [this fix](https://github.com/signalpoint/DrupalGap/issues/680#issuecomment-189901815) do?

`drupalgap_remove_pages_from_dom()` does not remove all pages (of course except the current) from dom due to bug in the code. Which bug? Re-indexing array while it iterating. See example here https://jsfiddle.net/ekjr8kr2/6/. This is why in `drupalgap_remove_pages_from_dom()` "for" loop must be done on an array copy instead of original array. Compare results of jsfiddle above with this one https://jsfiddle.net/Lm9qfxne/2/

**Comment by jomarocas** [comment]
@Digeridoo @signalpoint 

hi i have several problems with user logout and how implement the best way for the app, my principal problem is

i have a footer that only see the user that have role 6 and when user logout i need this user see other thing

this is my function

```
function custom_module_bienvenido() {
  try {
    var account = Drupal.user;
    var roles = account.roles;
    if (account.uid == 0) {
      drupalgap_goto('node/11',{transition:'slide'});
    }else if(roles['4']){
      drupalgap_goto('menu-principal-acompanante',{transition:'slide'});
    }else if(roles['5'] ){
      drupalgap_goto('menu-principal',{transition:'slide'});
    }else if(roles['3']){
      drupalgap_goto('menu-principal',{transition:'slide'}); 
    }else{
      drupalgap_goto('menu-principal-acompanante',{transition:'slide'});
    }
  }
  catch (error) { console.log('custom_module_bienvenido - ' + error); }
}
```

i put transition:slide because i find a bug that if i make this custom home, when i visiting any page appear the home for miliseconds and load the page that i visit, and i need add to all pages transition:slide for erase this bug.

i go back to bug, when user logout to the page, appear the footer that only should appear to user that make login in the app, then i add reloadpage:true in user:logout and dissapear the bug, but later of login and logout, go back the footer when user is logout, no working all well

any more ideas? thanks

**Comment by signalpoint** [comment]
@Digeridoo thank you, you were right. Without making a copy of `drupalgap.pages`, that was causing big problems. I've taken your code changes and committed them.

@jomarocas Try the latest drupalgap.min.js file, and I think you'll may want to always have the `reloadPage` option set to `true` on your logout link(s).
