### ISSUE TITLE
DrupalGap App runs in the Simulator without problems but gets stucked on splash screen when running it on an iPhone

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#701]
Hi,

I have just created an iOS App of the DrupalGap app, which comes with the SDK.

When running it in the Simulator the app works.

When starting it on my iPhone it gets sucked on the spash screen. Here is the Xcode Debug log:

```
2016-02-09 16:38:45.471 DiaryPad[1945:597935] Using UIWebView
2016-02-09 16:38:45.475 DiaryPad[1945:597935] [CDVTimer][handleopenurl] 0.133991ms
2016-02-09 16:38:45.478 DiaryPad[1945:597935] [CDVTimer][intentandnavigationfilter] 2.825975ms
2016-02-09 16:38:45.478 DiaryPad[1945:597935] [CDVTimer][gesturehandler] 0.104964ms
2016-02-09 16:38:45.506 DiaryPad[1945:597935] [CDVTimer][file] 27.700961ms
2016-02-09 16:38:45.506 DiaryPad[1945:597935] [CDVTimer][TotalPluginStartup] 31.511009ms
2016-02-09 16:38:45.775 DiaryPad[1945:597935] Resetting plugins due to page load.
2016-02-09 16:38:46.286 DiaryPad[1945:597935] Finished load of: file:///var/mobile/Containers/Bundle/Application/FFF3E977-23DB-4322-B5A4-553D52D7644F/DiaryPad.app/www/index.html
```

Any ideas why it works in the Emulator but not on the iPhone?

**Comment by signalpoint** [comment]
@luxio Include the `cordova.js` file in your `index.html` file and copy the `cordova.js` file from the `platform_www` directory in the cordova project, otherwise there are a bunch of other discussions about this: http://docs.drupalgap.org/7/Install/Troubleshoot/WSOD - Carefully follow the instructions here, there are many key steps: http://docs.drupalgap.org/7/Compiling_a_Mobile_Application

**Comment by luxio** [comment]
The `cordova.js`was already included. Copying the `cordova.js` file did not change anything. 

After a while, I get this message in the Xcode debug log:

```
Message from debugger: Terminated due to memory issue
```

I don't understand why it runs in the iOS Simulator, but not on the real device.

**Comment by icoonh** [comment]
Hello,

Tyler, firstly thanks for your wonderful efforts. `/**my first comment here**/`

I can confirm that this exact issue happens in iphone 6 and iphone 6s simulators in xcode with a previously working code. This issue doesn't occur in earlier iphone models' simulators or devices. Works flawlessly in iphone 4 and 5. However 1 in 5-6 installation tries the app also fires in iphone 6 and later simulators, but goes to wsod after a little while. I didn't encounter the insufficient memory log yet though in my tests. I initially thought it was due to cordova push plugin, but since a clean install also encountered this issue i am ruling that out.

In summary this happens in iphones 6 with ios 9+, after resetting plugins and loading index.html. drupal onload function doesn't get through.

The issue takes place with these configurations:

```
Xcode 7.2 (7C68)
cordova updated to 6.0.0
ios platform updated to 4.0.1
```

Plugins:

```
cordova-plugin-app-event 1.1.0 "Application Events"
cordova-plugin-camera 2.1.0 "Camera"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-file 4.1.0 "File"
cordova-plugin-file-transfer 1.5.0 "File Transfer"
cordova-plugin-inappbrowser 1.2.1 "InAppBrowser"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-whitelist 1.2.1 "Whitelist"
de.appplant.cordova.plugin.badge 0.7.1 "Cordova Badge Plugin"
phonegap-plugin-push 1.5.3 "PushPlugin"
```

Used to have statusbar and geolocation plugins too, but removed them while looking for the cause. There seems to be no problem regarding Android versions.

Looking for a solution too, I'll let you know if I manage to overcome the problem.

**Comment by signalpoint** [comment]
@icoonh Try downgrading to Cordova 5, I haven't tried 6 yet.

@luxio What version of Cordova are you using?

**Comment by icoonh** [comment]
@signalpoint downgraded to Cordova 5.4.1 and ios platform 3.9.2 with **'Enable Bitcode : No'**.

After downgrading Cordova had similar issues with `ios@4.0.x,` so removed its platform completely before adding `ios@3.9.2.` Now it seems to be working fine in all ios phones.

Thank you for your advice.

**Comment by luxio** [comment]
@signalpoint I was using `cordova@6.0.0`. After downgrading to `cordova@5.4.1`, the problems disappeared.

Thank you for your help.
