### ISSUE TITLE
Render picture of node's author

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#725]
In the node object in `hook_node_page_view_alter_type()` there is an attribute called `picture`which contains the fid of the author's picture.  What is the best way to get the uri of the picture in order to render in the node? 

`file_load()` would load the complete picture, but I only need the uri to download a smaller size with imagestyles.

**Comment by signalpoint** [comment]
@luxio I'd like to see this solution implemented on the Drupal side of things. i.e. http://cgit.drupalcode.org/services/tree/docs/services.alter.api.php?h=7.x-3.x#n42

I'd vote to post process the loading of any node on the server side, and grab the uri to the author's picture, and bundle it somewhere in the node object, so it is spit back via JSON. This would be cool if it was in the DrupalGap module, but for a quick resolution, you could toss it into a custom Drupal module, and then use `hook_node_page_view_alter_type()` to print out the picture.

This would mean only one call to the server for the node, instead of one call for the node, then one call for the picture.

**Comment by luxio** [comment]
Are you interested in a pull request for including the uri pictures in the node retrieves?

**Comment by signalpoint** [comment]
@luxio thank you that'd be great. It would need to be a patch though, since this should be done server side in the DrupalGap Drupal module.

**Comment by luxio** [comment]
I have uploaded a fist [patch](https://www.drupal.org/node/2680377).

**Comment by signalpoint** [comment]
Closing in favor of https://www.drupal.org/node/2680377
