### ISSUE TITLE
Is it possible to show a webform node without the form?

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#752]
When displaying a webform, I want to decide, if the node is shown with our without the webform form.

Sure, I could hide it with css in my theme.

Or maybe I could check for a `hidden`property in `webform_entity_post_render_content()`

What do you think?

**Comment by signalpoint** [comment]
@luxio Is that a setting up in Drupal? Or is this just a feature for your app in particular?

**Comment by luxio** [comment]
In Drupal I have a 2 view modes. One with the webform and one without the webform. 

Although I have set the webform to hidden in the `DrupalGap` view mode, it is always shown in the App.

**Comment by signalpoint** [comment]
@luxio Interesting, I didn't realize there was a "row" for a webform in the Display mode. I guess the webform module needs to be expanded to support that feature. I'm going to close this issue here, feel free to open a new one under the https://github.com/signalpoint/webform issue queue.

P.S. I'm trying to encourage folks to post issues about contrib modules in those corresponding issue queues, because the DrupalGap issue queue is getting pretty hefty.
