### ISSUE TITLE
D8 - hooks for slidemenu does nothing

### ISSUE THREAD

**Issue by jfcartier** [signalpoint/DrupalGap#756]
Hi

I try to implement a [slide menu](http://docs.drupalgap.org/8/Menus/Slide_Menus) and the hooks provided in the documentation doesnt seem to work. I've created my module, added the _block_info and _block_view functions, called the script in index.html, modified settings.js, and nothing happened.

So I looked Inside drupalgap.js and the hooks doesnt seem to be supported. Am I wrong or am I missing something here?
I think I got the latest version 2016-03-14 (https://www.drupal.org/node/2606456).

Does anybody successfully added a slide menu on a Drupal 8 drupalgap ? 

Thank you

**Comment by signalpoint** [comment]
@jfcartier I'm glad you are adventurous and trying the D8 version. Unfortunately it hasn't yet reached an Alpha version, so it is quite unstable, and I'm sorry that the docs are very misleading because they are incomplete at this point (and often are just a copy of the D7 docs, which makes most of them obsolete).

I personally haven't made a slide menu yet in D8, but the DrupalGap 8 blocks are pretty stable, so you can probably built a slide menu using a css framework: http://docs.drupalgap.org/8/Blocks

**Comment by signalpoint** [comment]
Hello @jfcartier and others. Good news, slide menus are now very easy in DrupalGap 8 using the Curtain Widget: http://docs.drupalgap.org/8/Widgets/Curtain_Widget
