### ISSUE TITLE
Rules are not triggered for editing/saving nodes

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#763]
I have two rules set up on the website. One triggers on new node creation, and one triggers on node resaving.

Both rules work on the website.

In DG app, only new node creation rule gets triggered.

Where would I start looking to figure out why the node resaving rule isn't getting triggered?

**Comment by signalpoint** [comment]
@mkinnan This sounds like it'd be an issue somewhere up in Drupal with Services vs. Rules. Since DrupalGap uses jDrupal to handle node save/load/update/delete, and jDrupal think just hits Services endpoints, I think it'd be up to Services and/or Rules to detect when/where/why a node update wouldn't trigger a Rule. Interesting issue though, thank you for reporting. I haven't had much experience with the need for Rules in an app and am surprised a node update rule wouldn't be firing.

**Comment by pierpa68** [comment]
@mkinnan, @signalpoint 
I made some work today involving the use of rules with DG and can confirm that rules get triggered on node creation as well as on node saving. I haven't tryed with node deletion.

HTH

**Comment by mkinnan** [comment]
@pierpa68 @signalpoint ... hmm ... maybe I'm having issues because of the date module issues even though the node does get resaved.

**Comment by mkinnan** [comment]
Things are working fine. Not sure what the issue was.
