### ISSUE TITLE
select multiple change the form to render

### ISSUE THREAD

**Issue by jomarocas** [signalpoint/DrupalGap#796]
Hi @signalpoint i have a select that have multiple values in user register form, when i go to user register and  click in a select that have multiple values appear in home page and the select effectly but funcionality custom for this form broken, then i need implement the select with multiple options, i can alter the select functionality of a select to change the behavior? i need implement same that documentation of juqery mobile in section multiple selects
http://demos.jquerymobile.com/1.0.1/docs/forms/selects/custom.html

how can alter the select, please

thanks 

appear 
[http://imgur.com/iWWdkje](url)

 i need 
[http://imgur.com/DmUTXF1](url)

**Comment by jomarocas** [comment]
ok the bug is for my part, i have a large items  for select and always render in new page, i dont know why but i think in other thing, render something values and later a button to write the option, is posible with drupalgap?

**Comment by signalpoint** [comment]
@jomarocas I'd first recommend always referring to the latest jQM docs here: https://api.jquerymobile.com/

Then here's the docs for select lists: https://api.jquerymobile.com/selectmenu/

To help further, I'd need to see the code you are using to make the "appear" select list.

**Comment by jomarocas** [comment]
hi @signalpoint the select list is a field select in drupal that have unllimited fields for select and lot of values and appear in the register form, i read from this url https://api.jquerymobile.com/selectmenu/ that is not possible make that i need. maybe the explication is this for jquery mobile, i need no render in new page, but is not possible

"When a select is large enough to where the menu will open in a new page, the placeholder text is displayed in the button when no items are selected, and the label text is displayed in the menu's header. This differs from smaller overlay menus where the placeholder text is displayed in both the button and the header, and from full-page single selects where the placeholder text is not used at all. "

**Comment by signalpoint** [comment]
@jomarocas There is a long standing issue with the Services module that must be resolved before DrupalGap can properly handle unlimited value fields: https://www.drupal.org/node/2224803

Until then you could use the patch, and then in DG use a services preprocess and probably some form alterations to build your widget as needed.

**Comment by jomarocas** [comment]
hi @signalpoint i make something while services working in this. but i have a problem

i create a field in user register a select list with 9 values and i make the button hide and show for create a button that make "add more field",  this working good but the problem is when i send values to register user

this error appear in dblog

```
services
?q=drupalgap/user/register.json
```

but when i see the values to send
the first element in "field_medicamentos_habituales" appear blank space, the first element in array and later of submit tells "medicamentos_habituales" is detect an option ilegal, contact your site administer.

```
           [field_tipo_cancer] => Array
                (
                    [und] => Array
                        (
                            [value] => Cerebro
                        )

                )

            [field_medicamentos_habituales] => Array
                (
                    [und] => Array
                        (
                            [value] => Array
                                (
                                    [0] => 
                                    [1] => Etoposido
                                    [2] => Placlitaxel
                                    [3] => Vinblastina
                                    [4] => Bleomicina
                                )

                        )

                )
```

and folloew the continues error in dblog

Warning: Illegal offset type in isset or empty in _form_validate() (líne 1374 of appoconlogia/includes/form.inc).

and 

Warning: htmlspecialchars() expects parameter 1 to be string, array given in check_plain() (líne 1576 of /includes/bootstrap.inc).

this error is for service or drupalgap when send the values? thanks @signalpoint

**Comment by gs9999** [comment]
Aloha Tyler,

I got my custom service with arguments working for saving fields and user values on the drupal side (PHP) with a custom drupalgap form.  However, on a second form I am creating, some of my fields on the drupalgap side save multiple values (some up to 12 possible values can be selected).  I was registering in my_module.services.inc. the multiple value param as an array.  

My question is per this thread, is there still an issue with passing multiple values though the custom service and custom form.  Or, how do I access the value that is a multiple value field in the my_module.resource.inc function that processes the multi value field?

I tried as a resource function --

function my_module_user_save($param_one, $param_two) {

$user_object = user_load($param_one);

$user_object->field_one['und'][0]['value'] = $param_two[0];
$user_object->field_two['und'[0]['value'] = $param_two[1];
 
user_save($user_object, $user_object);

}
I am getting a 500 error, which means the resource function is not computing correctly.


However, I believe that I am accessing the a $param_two array incorrectly, or its not being passed or registered correctly either in my my_module_form_page.js custom form javascript file. or the services.inc, because when I don't pass $param_two, or only send one value through $param_two, I get a 200 response from the service in the firefox poster app.

Is there just a simple snafu on the services module side that prevents the application of what I am trying to do, or should it work out of the box?  ??

**Comment by gs9999** [comment]
Aloha Tyler,

I solved the problem, and the script works as designed.  The variable passes as an array, and the above example works perfectly.  I am using a custom service with arguments and my own custom forms.  This method does not run into the problems relating to using pre-defined drupalgap user edit pages with entities.

Sorry for the premature write-up,

GS

**Comment by sangasgar** [comment]
gs9999
Please write your code
