### ISSUE TITLE
How to create an own module for an already supported field?

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#813]
Hi,

I want to start developing module for the File field which allows uploading multiple raw files to Drupal.

There is already a file.js module in DrupalGap. What would be the easiest way to develop an own version of the file module without having to make a new version of drupalgap-7.0.1.min.js?

**Comment by signalpoint** [comment]
@luxio I think you could just make a `app/modules/custom/file/file.js`, include it in `settings.js`, and any function you put in there should overwrite DG core, because those functions will be included after core is included. I don't think JavaScript cares about this, it's a little sloppy but would get the job done.

**Comment by luxio** [comment]
Thx, this seems to work.
