### ISSUE TITLE
Caching Does not Appear to Work

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/DrupalGap#814]
Not sure how to disable node caching in settings.js. 

I tried setting global to false ... also tried setting global to true and expiration to 1. The only way i can clear cache of a node with comments is to restart app.

**Comment by mkinnan** [comment]
Clearing drupal cache (_drush cc all_) has no effect. That tells me it must be caching on the phone.

**Comment by signalpoint** [comment]
@mkinnan Is this happening in compiled mode? I've noticed lately that compiled Android apps are caching GET requests at the "phone" level. I've hacked my way around this by using  http://api.drupalgap.org/7/global.html#hook_services_preprocess to append a timestamp to each request path.

i.e. `path += time();`

This is less than ideal since that means no caching at all will be possible, but it definitely gets around the problem. It may actually have to do with the web host too, perhaps they are putting a cache header on the response, then the Android phone listens to that and keeps things cached with future GET requests.

All in all, I'd be concerned if this happens in web app mode, then I'd blame jDrupal, otherwise I'm fairly certain this is a web host / compiled problem.

**Comment by mkinnan** [comment]
This is happening in compiled Android AND in web-app mode!

**Comment by mkinnan** [comment]
I have to CTRL+R in Chrome to get cached cleared ... settings.js is set for caching enabled and expiration for 1 second. Mode is set for 'web-app'.

**Comment by mkinnan** [comment]
Is there a parameter that is supposed to be added to the **path** time modification above?

**Comment by signalpoint** [comment]
@mkinnan You're right, sorry it should be something like: `path += '&timestamp=' + time();`

**Comment by mkinnan** [comment]
@signalpoint It is still caching the node. I can see the timestamp amended to the **path** when viewing a node. When I navigate to my view with the list of nodes, and then click on the same node again the **path** isn't being shown in my `console.log` debugging telling me that `hook_services_preprocess` isn't being called after the first time a node is viewed.

**Comment by signalpoint** [comment]
@mkinnan Are you setting a `reloadPage` option to true on your links to the node? Just a reminder that pages stay in the app's DOM once they've been visited, so when navigating back to a page, it will already be loaded (unless you programmatically remove it or set the `reloadPage` option on the link).

```
var html = l(t('Foo'), 'bar', { reloadPage: true });
```

**Comment by mkinnan** [comment]
Ahh, not adding the reload page in the views pages for each node is likely my issue ...

**Comment by mkinnan** [comment]
Yup. That was the issue. Thanks!
