### ISSUE TITLE
drupalgap_item_list_populate() fails on subsequent page loads via different choice

### ISSUE THREAD

**Issue by obsidiandesign** [signalpoint/DrupalGap#82]
When re-visiting a list of choices, two behaviors happen on subsequent loads of the same list.
Given items in a list, A, B, C, D:
1) User chooses A on first page visit.  Page loads properly.  User visits the home page (or any other page) then visits the list page again.  User selects A.  Page loads properly.
2) User chooses A on first page visit.  Page loads properly.  User visits the home page (or any other page) then visits the list page again.  User selects B, C, D - page loads but with nothing displayed.

This behavior happens both to a subsequent list page or a page with text.  Any calls to load the page data fails.  However, console.log() properly shows the data that should be in the list or the page and the call to drupalgap_item_list_populate() on the second try.

**Comment by obsidiandesign** [comment]
Looking through the issue queue, this issue may or may not be related to #48 or even #81 since it relates to subsequent page rendering issues.

**Comment by signalpoint** [comment]
@obsidiandesign - I was looking at your forked copy of DrupalGap, it appears to be quite a few commits behind. Will you please verify you have pulled all the latest code changes. Here is what looks different:

https://github.com/signalpoint/DrupalGap/compare/obsidiandesign:7.x-1.x-alpha...signalpoint:7.x-1.x-alpha

After pulling in the latest, does the behavior you describe above still occur?

**Comment by obsidiandesign** [comment]
@signalpoint  - Sorry, I'm not a git expert by any means.  Apparently I forked the repository properly but on my local machine was using the code from signalpoint/DrupalGap instead of my fork.  I have since switched to the fork and properly updated it; the issue persists.  I had pulled from your repository earlier this afternoon, but have fetched the latest changes to double-check my work.

**Comment by signalpoint** [comment]
@obsidiandesign - No problem, thanks for updating your fork. This will allow you to make improvements to DrupalGap core if you find something that doesn't work for you. Then you can issue a Pull Request and it can be brought into DrupalGap core.

I wasn't able to reproduce what you mentioned. Is this happening on the default 'Content' page provided by DrupalGap. I.E. You view the list of recent nodes, click on node A, navigate back to Home, navigate back to Content, then click on node B? If so, node B displays fine for me, but the comments don't show up.

Or is this happening with code that you've put into a custom DrupalGap module? Feel free to explain more here, or contact me in IRC, thanks!

**Comment by signalpoint** [comment]
@obsidiandesign - from our IRC chat, this is what was happening: 

http://pastebin.com/himAGpxb

frankenstein

So you click on node A, then go back to Home, then click on node B and nothing displays?

bryanUC

that's what I thought, although I thought maybe I was misusing drupalgap_list_item_populate or something
yes
 although it's not a node on the 2nd page, it's another list

frankenstein

 Eeer yeah, a list.

bryanUC

but yeah, same setup & such

frankenstein

What if you give your list a dynamic ID?

bryanUC

Where would I go about doing that?

frankenstein

{'id':'teams_list_items_' + age_group}

 then as long as age_group contains valid html for an id attribute, that should be OK
 This is definitely because as you navigate around, the previous pages stays in the DOM, and since the next page gets loaded and has the exact same html ID on the list, the older pages list gets updated.

bryanUC

ah, very cool.  That works perfectly!

frankenstein

Sweet.

bryanUC

I was still thinking in the sense of php - next page load is a totally new experience
 So it's not a bug, it's a "gotcha" when it comes to dynamic lists.  They need dynamic id's

frankenstein

A little of both, I'd consider it a bug I guess. It could be fixed if we remove old pages from the DOM, but I haven't figured out an appropriate time to do that since there always needs to be 2 pages in the DOM to do changePage transitions properly.
 Thanks for pointing this out though.

bryanUC

Sure!

**Comment by signalpoint** [comment]
Update: Previously visited pages stay in the DOM, and when you navigate back to them, they are no longer removed and rebuilt. https://github.com/signalpoint/DrupalGap/issues/88
