### ISSUE TITLE
Views Exposed Filter Item Limit

### ISSUE THREAD

**Issue by ghost** [signalpoint/DrupalGap#862]
Hi, 
I created a page with exposed filter with taxonomy term. And exposed items display fine. But, when I limit exposed item by selecting 3 items from many items, it not working... drupalgap display all taxonomy term items.

How can I solve it? Please Help.

**Comment by signalpoint** [comment]
Use inline JavaScript to manually remove them after they've been injected into the select list. http://docs.drupalgap.org/7/Pages/Page_Events/Inline_JavaScript

**Comment by ghost** [comment]
Hi Signalpoint, Thanx for quick reply.
Maybe, it will be more easy - if I create custom select option list and re-render views when change select  option. 

**Here, I create a page with json data -** 
[drupalgap-views-page-updated.txt](https://github.com/signalpoint/DrupalGap/files/507731/drupalgap-views-page-updated.txt)

My problem is - **how to re-render current views page on select onchange?**
Please help.

**Comment by signalpoint** [comment]
@tazimhossain That is usually what I do, because it's often too difficult to try and support all the views exposed filters out there.

This VIS module has some examples of how to dynamically render a view: https://github.com/signalpoint/views_infinite_scroll/blob/7.x-1.x/views_infinite_scroll.js

Otherwise the `views_embed_view` function is probably what you're looking for: `views_embed_view(path, options)`: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/views/views.js#L462

**Comment by signalpoint** [comment]
Regarding [Views Exposed Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Exposed_Filters), after much consideration I've decided to abandon support and further development on the topic. The more flexible alternative is to utilize [Views Contextual Filters within DrupalGap](http://docs.drupalgap.org/7/Views/Views_Contextual_Filters) instead.
