### ISSUE TITLE
How to detect in Drupal if it is accessed by DG

### ISSUE THREAD

**Issue by luxio** [signalpoint/DrupalGap#910]
Is there a simple way to detect, if a user is currently accessing content with the Drupal Gap Client?

**Comment by signalpoint** [comment]
@luxio All the service resource URLs are prefixed with `drupalgap`, so that's an easy way using Drupal's `arg()` function:

```
if (arg(0) == 'drupalgap') {
  // We are in DrupalGap, do something with PHP...
}
```

Then I also like to prefix all my Views JSON pages with `drupalgap`, so the same can be used when they are doing GET on those pages.

Of course if you've changed your api endpoint name, use that instead of `drupalgap`.

**Comment by luxio** [comment]
Thanks. Simple but good.
