### ISSUE TITLE
Page Arguments in 8

### ISSUE THREAD

**Issue by Nicolas-Bouteille** [signalpoint/DrupalGap#960]
Hi,

I can't seem to find out how route / page arguments is handled in DrupalGap 8.
The doc exists for version 7 http://docs.drupalgap.org/7/Pages/Page_Arguments
but not for version 8 apparently.

thanks!

**Comment by Nicolas-Bouteille** [comment]
I am trying to test the example of the bucket widget
http://docs.drupalgap.org/8/Widgets/Bucket_Widget
but I need to pass the node id as argument... and I can't find out how

**Comment by Nicolas-Bouteille** [comment]
Ok for those looking for the same info, I found it by looking at the drupalgap/src/modules/node/node.js file

` routes["node"] = {
    "path": "/node\/(.*)",
    "defaults": {
      "_controller": function(nid) {`

So the wildcard is (.*)
No need to mention the position in the path like page_arguments: [1] or something...
There's one thing I still wonder though: why use `\/` instead of just / which actually works... ?

**Comment by signalpoint** [comment]
@Nicolas-Bouteille Thank you for digging into the router system in DG8, not many have ventured that far ;)

> So the wildcard is (.*)
> No need to mention the position in the path like page_arguments: [1] or something...

Yes, the wildcard is `(.*)`, and the router should automatically feed that value into your `_controller`. Multiple values should work as well, and it'll pass them all.

> There's one thing I still wonder though: why use \/ instead of just / which actually works... ?

The [router in DrupalGap 8](https://github.com/signalpoint/DrupalGap/blob/8.x-1.x/src/includes/router.inc.js) was inspired by and evolved from [this post](http://krasimirtsonev.com/blog/article/A-modern-JavaScript-router-in-100-lines-history-api-pushState-hash-url).

To be honest, I always thought we had to use the `\` to escape the `/` character in the path (since this string gets fed into regex), and I never actually tried to use it without the `\`. That is great news that it works without it, great catch.

> I can't seem to find out how route / page arguments is handled in DrupalGap 8.

I've just now added this page to the docs: http://docs.drupalgap.org/8/Pages/Page_Arguments

Thank you for your assistance, if you have a moment please double check the new example.

**Comment by Nicolas-Bouteille** [comment]
Thank you for your feedback. It is really pleasant to receive it so fast. I feel like I am helping out and that makes me want to do it even more ^^
I'll try the new example!
